### ISSUE TITLE
Add desktop entry and icon

### ISSUE THREAD

**Issue by lakinduakash** [lakinduakash/linux-wifi-hotspot#10]

**Comment by fabricio-godoi** [comment]
I'm a little lost in the install process, so if anyone would like to help in this regard, I just create a .desktop example to start the program with sudo privileges.

`[Desktop Entry]
Type=Application
Name=WifiHotspot
Icon={YOUR ICON HERE}
Exec=sh -c 'pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sudo /usr/bin/wihotspot'
Terminal=false
Categories=System
Keywords=Hotspot;WiFi
`

**Comment by lakinduakash** [comment]
Hi,
You can add .desktop file and let it copy relevant directory while installation. You can modify the install and uninstall sections in the Makefile to do that. Then send a PR
:)

**Comment by fabricio-godoi** [comment]
@lakinduakash Greetings!
I think this issue could be closed if the previous PR satisfy its requirements.
