### ISSUE TITLE
Unable to join the network - iPhone 6s

### ISSUE THREAD

**Issue by muhammadabrar9999** [lakinduakash/linux-wifi-hotspot#100]
I was successful in installation of create_ap and have used the HOTSPOT once but for second time (in office) I was facing this issue:

> root@C-243:/home/coeus# sudo create_ap wlp5s0 wlp5s0 EasyLinux easylogics
> Config dir: /tmp/create_ap.wlp5s0.conf.L82MRbtg
> PID: 60397
> Network Manager found, set ap0 as unmanaged device... DONE
> wlp5s0 is already associated with channel 36 (5180 MHz), fallback to channel 36
> Creating a virtual WiFi interface... ap0 created.
> 
> ERROR: Your adapter can not transmit to channel 36, frequency band 5GHz.
> 
> 
> Doing cleanup.. done

AFTER than, I've tried to fix this by doing 2 solutions provided by oblique, but haven't found the solution.
Now, I've moved to this repo. and found this as maintained.

I'm successful in implementing all the steps of this wifi hotspot app. but whenever I create the HOTSPOT manually by opening app from command line: below is the script runs;

> root@C-243:/home/coeus# wihotspot
> mac filter file /etc/hostapd/hostapd.accept 
> aa:aa:aa:aa:aa:aa
> aa:aa:aa:aa:aa:ff
> aa:aa:aa:aa:aa:ee
> 
> pkexec --user root create_ap wlp5s0 lo 'EasyLinux' '123456789' --mkconfig /etc/create_ap.conf --freq-band 2.4 --mac aa:aa:aa:aa:aa:ff --mac-filter 1 
> Config options written to '/etc/create_ap.conf'
> Trying to kill create_ap instance associated with 125427...
> mac filter file /etc/hostapd/hostapd.accept 
> aa:aa:aa:aa:aa:aa
> aa:aa:aa:aa:aa:ff
> aa:aa:aa:aa:aa:ee
> 
> pkexec --user root create_ap wlp5s0 wlp5s0 'EasyLinux' '' --mkconfig /etc/create_ap.conf --freq-band 2.4 --mac aa:aa:aa:aa:aa:ff --mac-filter 1 
> Config options written to '/etc/create_ap.conf

Now, it shows a network on every phone but didn't connect to it, whenever I connect it it says "Unable to join the network"

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [20.04]

**Screenshots**
![ShowsNETWORK](https://user-images.githubusercontent.com/74533644/99233979-c6d1e200-2815-11eb-9f06-9a2c06b23b05.jpeg)
![UNABLEtoConnect](https://user-images.githubusercontent.com/74533644/99233988-c9343c00-2815-11eb-9ef5-f5d57ff28f01.jpeg)
![Screenshot from 2020-11-16 14-08-30](https://user-images.githubusercontent.com/74533644/99233990-ca656900-2815-11eb-8656-5b679383dd47.png)

**Comment by lakinduakash** [comment]
Please disable the mac filter.. It is the problem. Mac filter only allows
connect to devices with provided mac addresses
