### ISSUE TITLE
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time

### ISSUE THREAD

**Issue by TornaxO7** [lakinduakash/linux-wifi-hotspot#101]
**Describe the bug**
If I start `wihotspot` like this **on my raspberry pi 3B+** with `sudo wihotspot` than this pops up:
```
(wihotspot-gui:5479): dbind-WARNING **: 10:16:09.237: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
pkexec --user root create_ap wlan0 eth0 ' Tornax-Pi' 'ChiBaYanni16122019' --mkconfig /etc/create_ap.conf --freq-band 2.4
Config options written to '/etc/create_ap.conf'
WARN: brmfmac driver doesn't work properly with virtual interfaces and
      it can cause kernel panic. For this reason we disallow virtual
      interfaces for your adapter.
      For more info: https://github.com/oblique/create_ap/issues/203
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time
Command not found or exited with error status
```
but it's also connected with an ethernet cable. So shouldn't the (in built) wifi-adapter be free?

**To Reproduce**
1. Connect a raspberry pi with an ethernet cable
2. ssh into it
3. execute `sudo wihotspot`

**Expected behavior**
I expected that it works.

**Screenshots**
Current settings:
![image](https://user-images.githubusercontent.com/50843046/99510619-96aa5080-2987-11eb-9329-c49712b29ddf.png)

The output after clicking the `Create Hotspot` button:
![image](https://user-images.githubusercontent.com/50843046/99510790-c48f9500-2987-11eb-8716-92217e12be4f.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/50843046/99510999-fe609b80-2987-11eb-8021-528469c04ce4.png)

The version should be the latest. I just installed a new raspbian image on my raspberry pi with `rpi-imager`.

**Comment by lakinduakash** [comment]
Can you try with no-virt option enabled?

**Comment by TornaxO7** [comment]
I'm sorry for the late answer!!

So here are the settings:
![image](https://user-images.githubusercontent.com/50843046/103490317-5c9feb80-4e1b-11eb-8927-bb3935146a4c.png)

And that's the output:
```
pkexec --user root create_ap wlan0 eth0 'My Raspberry Pi' 'BestPasswordEver' --mkconfig /etc/create_ap.conf --freq-band 2.4 --no-virt
Config options written to '/etc/create_ap.conf'
WARN: brmfmac driver doesn't work properly with virtual interfaces and
      it can cause kernel panic. For this reason we disallow virtual
      interfaces for your adapter.
      For more info: https://github.com/oblique/create_ap/issues/203
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time
Command not found or exited with error status
```
Well it looks like that I can't fix that ;-;

**Comment by lakinduakash** [comment]
This thread has some solutions [https://github.com/oblique/create_ap/issues/203](https://github.com/oblique/create_ap/issues/203 ). Might be helpful.

**Comment by TornaxO7** [comment]
Thanks for the link! I'll give it try and sorry again for letting you waiting for about 2 months.

**Comment by uree** [comment]
For anyone still encountering this issue in 2025 ... removing [this check](https://github.com/lakinduakash/linux-wifi-hotspot/blob/34fd80f2a7a87ad18b2eec88d92279db9228c7c3/src/scripts/create_ap#L305-L311) in create_ap allows you to run the command(s) on Raspberry Pi without any issues. The above mentioned discussion in [oblique/create_ap#203](https://github.com/oblique/create_ap/issues/203) is informative as to why.
 
I have tried these on Raspberry Pi 5 & Ubuntu Server 24.04.3 LTS and they work well:
```
sudo create_ap -n  wlan0 eth0 ssid pass
sudo create_ap wlan0 eth0 ssid pass
sudo create_ap wlan0 wlan0 ssid pass
```
