### ISSUE TITLE
Wifi interface drop down disabled

### ISSUE THREAD

**Issue by ShrirajHegde** [lakinduakash/linux-wifi-hotspot#102]
**Describe the bug**

**To Reproduce**
1. Go to WiHotspot
2. Click on the Wifi interface

**Expected behavior**
Be able to select wifi interface

**Screenshots**

![image](https://user-images.githubusercontent.com/66936172/99705107-4df5b300-2abf-11eb-96f7-f6968439535e.png)
Unable to select anywifi interface at all

**Desktop (please complete the following information):**
 - OS:Arch linux
 - Version : 5.9.9-arch1-1

**Comment by lakinduakash** [comment]
Did you turn on the wifi from the system?

Did you install the all the dependencies? Check`iw` or `iwconfig` commands
work.

**Comment by ShrirajHegde** [comment]
iwconfig was missing and still is


but installing from AUR made it work

Thanks :+1:
