### ISSUE TITLE
can't create discoverable AP in GUI

### ISSUE THREAD

**Issue by ybrhue** [lakinduakash/linux-wifi-hotspot#103]
**Describe the bug**
sudo create_ap --ieee80211ac --freq-band 2.4 wlp0s20f3 wlp0s20f3 YourSSID MyPassPhrase works in terminal but not in gui!

I select all the relevant fields (pw or no pw, SSID, 2,4 and ieee80211ac) but the AP is not discoverable.

**Desktop (please complete the following information):**
 - KDE latest from Manjaro Linux

**Additional context**
installed from aur

**Comment by lakinduakash** [comment]
Duplicate of #88
