### ISSUE TITLE
Sharing VPN connection

### ISSUE THREAD

**Issue by lautaroaimar** [lakinduakash/linux-wifi-hotspot#104]
Hey, first of all I wanna say thanks for this awesome application as it helped a lot in the previous days.
I was wondering if there's any constraint on sharing WiFi over same wlan board while being connected to a VPN, configured with gnome. 
Actually, WiFi sharing over same board works great until I connect to the vpn. Is there anyway or workaround to make that vpn sharing work?

#### About VPN
* IPv4 and IPv6 are in automatic mode
* Checkbox marked (Make available to other users)

**General config**
![image](https://user-images.githubusercontent.com/26861451/100780141-23252c00-33e8-11eb-83bd-1d271f0a6c8e.png)

**Advanced options**
![image](https://user-images.githubusercontent.com/26861451/100780281-48199f00-33e8-11eb-8119-adda3ff5d93e.png)

#### Command executed (took from src/scripts/readme.md)
`sudo create_ap wlo1 wlo1 MyAccessPoint MyPassPhrase`

Consider my adapter is recognized by ubuntu as *wlo1* and that this command works until i connect to the vpn as mentioned.

Sorry if this was more kinda stack-overflow question, I wanted to know not only how to make this use case works, but if was failing owing to some app limitation.

**Comment by lakinduakash** [comment]
Can you try with bridge internet sharing option. That might work. 
`create_ap -m bridge wlan0 vpnInterface MyAccessPoint MyPassPhrase`

**Comment by lautaroaimar** [comment]
Hey thanks for answering. Did try that unfortunately with no good results. In case sth else works I'll comment it right here, until then I'm closing the issue. Thx for your help :)

**Comment by aswallz** [comment]
#250
