### ISSUE TITLE
libhandy?

### ISSUE THREAD

**Issue by joshbowyer** [lakinduakash/linux-wifi-hotspot#107]
**Is your feature request related to a problem? Please describe.**
Could the UI use libhandy's library so it will be adaptive and work on Pinephone/Librem5? 

**Describe the solution you'd like**
Use libhandy

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by lakinduakash** [comment]
Currently, I don't have the capacity to implement that. If you can implement the UI part. Then I can consider merging that. Thanks for your suggestion.
