### ISSUE TITLE
Expose WPA version option

### ISSUE THREAD

**Issue by plonibarploni** [lakinduakash/linux-wifi-hotspot#111]
**Is your feature request related to a problem? Please describe.**
I want to be able to specify which version of WPA to use. By default it's set to 1+2 but I want to restrict it to just WPA2.

**Describe the solution you'd like**
There should be a checkbox/dropdown menu to select supported options.

**Describe alternatives you've considered**
It is possible already to do this using `create_ap` in the terminal directly, but a GUI option would be nice.

**Additional context**
```
Usage: create_ap [options] <wifi-interface> [<interface-with-internet>] [<access-point-name> [<passphrase>]]

Options:
<snip>
  -w <WPA version>        Use 1 for WPA, use 2 for WPA2, use 1+2 for both (default: 1+2)
```

**Comment by lakinduakash** [comment]
Adding more and more options in the UI makes it complex for the user. I think it is better if there is a separate section like `Advanced` and include such features. I don't know the importance of this feature. Otherwise, we can set the default to WPA2 in the script.

**Comment by plonibarploni** [comment]
> I think it is better if there is a separate section like Advanced and include such features.

Agreed.

> I don't know the importance of this feature.

This is the warning I get on my iPhone when  using WiFi Hotspot GUI:
![WPA/WPA2 (TKIP) is not considered secure. If this is your Wi-Fi network, configure the router to use WPA2 (AES) or WPA3 security type](https://user-images.githubusercontent.com/44826203/102408038-07f71680-3fbb-11eb-840c-c957886d61fd.png)

When I use `create_ap` with `-w 2` it doesn't give that warning anymore.

There's also a feature request on `create_ap` to add WPA3 support: https://github.com/oblique/create_ap/issues/404

**Comment by lakinduakash** [comment]
I will make the default as wpa2 in the script for now. Later I can implement the feature in UI.

**Comment by plonibarploni** [comment]
Interestingly, the source config file is already set to use WPA2 by default, however it is reset to WPA1+2 when creating a hotspot.

https://github.com/lakinduakash/linux-wifi-hotspot/blob/70a6d31fbaf8b1acd8aa3caa108dacca8561ae60/src/scripts/create_ap.conf#L3

**Comment by lakinduakash** [comment]
Oh, I see. I had no time to check it these days. Can you try to tackle that issue and fix it?

**Comment by plonibarploni** [comment]
It turns out that the `create_ap` script had the default set to 1+2, so it was overriding your config file.

**Comment by plonibarploni** [comment]
I've created a mockup for the interface with the added options for WPA Version, and also organized it a little better.
![image](https://user-images.githubusercontent.com/44826203/102955313-98de5e00-44a3-11eb-80c1-6caf978ec2e1.png)

**Comment by lakinduakash** [comment]
Reopening the issue for UI changes and for fixing always overriding the config value.

**Comment by lakinduakash** [comment]
> I've created a mockup for the interface with the added options for WPA Version, and also organized it a little better.
> ![image](https://user-images.githubusercontent.com/44826203/102955313-98de5e00-44a3-11eb-80c1-6caf978ec2e1.png)

UI looks fine. Can you fix that overriding issue and make a PR with this moke UI. I will integrate the UI changes with the C code.

**Comment by equetzal** [comment]
@lakinduakash, Sorry for bringing this up back. I see this got marked as completed but nothing got merged. Is into your plans to update the UI to bring up more details?
