### ISSUE TITLE
Spaces stripped from SSID & password

### ISSUE THREAD

**Issue by plonibarploni** [lakinduakash/linux-wifi-hotspot#112]
https://github.com/lakinduakash/linux-wifi-hotspot/blob/ea40a80eea3d9b4964be1921b3699332d0795f6c/src/ui/read_config.cpp#L60

The above code removes all spaces from the config file, so any spaces in the SSID or password set by the user are ignored.
I don't know why spaces are removed at all, but at least preserve those that part of the user input.

**Comment by lakinduakash** [comment]
That should be corrected for the password. But in other config values, we need to properly remove such as trailing whitespaces properly. otherwise, it can affect string comparisons when parsing the config file. I think we need to make an exception for the password field only.

**Comment by plonibarploni** [comment]
> I think we need to make an exception for the password field only.

Why not for the SSID? 'My Hotspot' is a valid SSID.

**Comment by lakinduakash** [comment]
Yes, I forgot that. Can you make a PR for this?
