### ISSUE TITLE
Option to build command line only

### ISSUE THREAD

**Issue by mrwm** [lakinduakash/linux-wifi-hotspot#116]
**Is your feature request related to a problem? Please describe.**
Coming from create_ap, it would be great to build the command line tools without the GUI. This will also make things easier in use cases with headless Raspberry Pi's and such.

**Describe the solution you'd like**
Remove dependancy on `libgtk-3-dev` and make it optional

**Describe alternatives you've considered**
It would also be cool if we can enable or disable building the GUI with a flag.

**Comment by mrwm** [comment]
The current solution with installing command line-only (just `create_ap`) is to follow instructions here:

https://github.com/lakinduakash/linux-wifi-hotspot/tree/master/src/scripts#generic

**Comment by lakinduakash** [comment]
That would be cool. I will include a section in main README.md about that
