### ISSUE TITLE
Can't create 5ghz hotspot without NetworkManager

### ISSUE THREAD

**Issue by ledlamp** [lakinduakash/linux-wifi-hotspot#123]
https://bs28.qonq.gq

It works if NetworkManager is running ~~but I need to disable it or I loose ethernet when I stop the hotspot (#122).~~
(No longer an issue for me but some people might not want to use NetworkManager).

**Comment by lakinduakash** [comment]
Need to analyse the root case and an alternative way without NetworkManager. For a temporary solution I can add NetworkManager as an dependency.

**Comment by yochananmarqos** [comment]
@ledlamp Do you have `hostapd` installed? It says it failed to run / command not found. What does that have to do With Newworkmanager?

**Comment by ledlamp** [comment]
Yes, the only difference was NetworkManager service was disabled.

**Comment by lakinduakash** [comment]
I will mark the network-manager as required for now
