### ISSUE TITLE
i need passwd to the gui 

### ISSUE THREAD

**Issue by pigstimemachine** [lakinduakash/linux-wifi-hotspot#125]
**Describe the bug**

when i click the GUI ,then it shows  Authentication is needed to run '/usr/bin/env'
 as the super user  . and ask me to input passwd  as root  ,but i input my root passwd ,it always show me the wrong tips  with "wrong passwd "  i believe i use the correct passwd ,how can i do ?  
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 18.04]

**Additional context**

**Comment by lakinduakash** [comment]
You should enter `sudo` password for the current user account. Otherwise, run as root ex: `sudo wihotspot`

**Comment by niksingh710** [comment]
> You should enter `sudo` password for the current user account. Otherwise, run as root ex: `sudo wihotspot`

What about Wayland ?? It does not allow to run GUI apps using Sudo 
It works with polkit but that asks password around 5 times and is kind of annoying.

sudo -E hotspot works but is there any other way?
using river Wayland in arch
