### ISSUE TITLE
do not use a hardcoded icon path in wifihotspot.desktop

### ISSUE THREAD

**Issue by freddii** [lakinduakash/linux-wifi-hotspot#128]
It would be useful to have not a hardcoded icon path in wifihotspot, so it can be easy replaced by another icon-themes.

**Comment by lakinduakash** [comment]
Yes. I aware about that. I need to make that icon compatible with more desktop environments. I only verified it with gnome. The logo should move to correct folders, then it can be used icon name instead of path. If you can add a PR for this issue.

**Comment by freddii** [comment]
Sorry, i don't know how to change that.

**Comment by yochananmarqos** [comment]
I do. #130

**Comment by lakinduakash** [comment]
Thanks @yochananmarqos
