### ISSUE TITLE
No Devices Can Connect to Hotspot

### ISSUE THREAD

**Issue by devin1126** [lakinduakash/linux-wifi-hotspot#131]
Hello,
I am using a raspberry pi 4 to enable a WiFi hotspot for my local devices. The hotspot itself is able to be enabled; however, when I try to connect other devices to the hotspot, it does not work. Here is the output that I am getting when I run "sudo create_ap wlan0 eth0 'DevRobotics' '022499ab'". The error can be seen in the picture below. 
![Hotspot_Err](https://user-images.githubusercontent.com/39745020/104959499-5293f600-59a0-11eb-8760-748bc01d255e.png)

As you can see, the hotspot can be enabled; however, when I connect my samsung note s20 to the hotspot, I get this error. When I try to connect to the hotspot with my laptop, no messages appear in the terminal. I only get a message from my laptop that states 'No Internet Connection. Disconnect Wireless'. My laptop is running ubuntu 16.04 as its OS. Any advice would be helpful. Thank you.

**Comment by lakinduakash** [comment]
Try  `create_ap` command line with multiple combinations such as enabling `ieee80211n` with `sudo create_ap --ieee80211n wlp0s20f3 wlp0s20f3 MyAccessPoint MyPassPhrase`

Refer here for more examples https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/src/scripts/README.md

**Comment by devin1126** [comment]
Hello,
This 'sudo create_ap --ieee80211n wlp0s20f3 wlp0s20f3 MyAccessPoint MyPassPhrase' solution actually worked for me. Thank you!
