### ISSUE TITLE
Doesn't work with RealTek rtl8821ce driver

### ISSUE THREAD

**Issue by a-sm** [lakinduakash/linux-wifi-hotspot#133]
I followed all the steps and installed the dependencies, when I open the program it listed my wifi connection as **wlp4s0**. But when I click the `Create hotspot` button it keeps stopping (just coming back to default state), status always reset to **Not running**.

 - OS: KDE Neon
 - Version Don't know the version but I downloaded and installed it on 21 January 2021, based on Ubuntu 20.04

**Comment by lakinduakash** [comment]
Can you run `wihotspot` from the terminal to get logs from GUI instead of launching from application menu?

Also, Can you try with the command line with this - `sudo create_ap --ieee80211n wlp4s0 wlp4s0 MyAccessPoint MyPassPhrase` and check whether works?

**Comment by a-sm** [comment]
Here's the output log

```
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time
```

Seems like my wifi hardware doesn't support it (in Linux) although in Windows it can create hotspot from same interface.

**Comment by lakinduakash** [comment]
I think that's a driver issue. For future reference can you put the driver details here? You can use `readlink /sys/class/net/wlp4s0/device/driver`. 

For more information like version, details run `sudo lshw -class network` and get the output from the corresponding network block.

**Comment by a-sm** [comment]
here's the output command from `readlink /sys/class/net/wlp4s0/device/driver`

**../../../../bus/pci/drivers/rtl8821ce**

My wifi adapter is Realtek and is has known issues that almost every Linux Distros don't have the built in driver and we have to install it manually using driver provided by tomaspinho.

**Comment by lakinduakash** [comment]
Even though https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/docs/howto/realtek.md has a solution for RealTek adapters, it is only supported with RealTek 8192 chipset. There might be a solution for this as well.
