### ISSUE TITLE
not all wifi interfaces(acces point interfaces) are showing in the gui/software/drop down menu

### ISSUE THREAD

**Issue by Linux-LIVING** [lakinduakash/linux-wifi-hotspot#141]
not all wifi interfaces (interface to use for acces point) are showing in the interface, works well for the first couple of days after installation but after a few reboots ... the ap interface/wifi interface doesnt apear anymore in the drop down menu

the internet interfaces show up correctly in the drop down menu... but the ap interfaces/Wifi interface does not..

its been an issue for a long time that keeps on happening, this always happens eventually after just a few uses, so i uninstall & reinstall it, but it doesnt fix the issue.. & ive reinstalled my debian based linux OS many times and the same thing always happens  .....so ive just kept on using create_ap by oblique for some years now, but i want to switch to linux-wifi-hotspot... 

i use two wireless cards.. 1-connected to internet    2-(wlan0) for acces point ,this works perfectly in create_ap, and works with linux-wifi-hotspot for a short time (a few days, then never again)  .... wireless card 2(wlan0) just stops appearing and never appears again
![Screenshot at 2021-02-12 01-15-36](https://user-images.githubusercontent.com/78952218/107744742-782acb80-6cd0-11eb-8a3c-22bc2e9ce398.png)
![Screenshot at 2021-02-12 01-15-50](https://user-images.githubusercontent.com/78952218/107744759-7f51d980-6cd0-11eb-84f2-23abd9faffc6.png)

, resulting in me no longer being able to use this software

OS being used:
Parrot Security OS
 
 -debian based
-kernel 5.10.15-051015-generic ... but the problem has existed for all previous kernels
- MATE desktop enviroment
 - currently using parrot os 4.10 ... but the problem has existed for all previous versions

-may be worth noting that: create_ap was always already installed before installing linux-wifi-hotspot from source

:::Steps to reproduce the behavior::

..just use the computer normaly..eventualy this bug happens

 

this is how ive been creating acces point in linux for years (with create_ap , but want to switch to linux-wifi-hotspot)....in linux-wifi-hotspot  the  acces point interfaces stops showing in the drop down menu (not all interfaces appear anymore & i need wlan0 to appear there so i can use it, it works the first couple of times (all interfaces appear in the acces point interfaces menu) but then this bug happens and they never show up there again)

![Screenshot at 2021-02-12 01-36-51](https://user-images.githubusercontent.com/78952218/107746375-f8523080-6cd2-11eb-88dc-4be80b733091.png)

**Comment by Linux-LIVING** [comment]
also happens in kali linux.... i am currently a first year software engineer student, but havent been able to fix this issue. thank you for your attention

**Comment by lakinduakash** [comment]
Hi, Thank you for reporting the issue, can you put the output of `iw dev`?

**Comment by Linux-LIVING** [comment]
Hello, thank you so much for such a quick response to my report.... im replying to your request;

output for  <  iw dev  >
![iw dev](https://user-images.githubusercontent.com/78952218/107822721-caed9d00-6d3b-11eb-91e3-e052657df29d.png)



output for  <  iw dev | awk '$1=="Interface"{print $2}'  >

![Screenshot at 2021-02-12 14-07-29](https://user-images.githubusercontent.com/78952218/107822842-00928600-6d3c-11eb-9b10-8071c6facb21.png)

**Comment by lakinduakash** [comment]
I think issue is fixed in v3.6.8. Can you check that?

**Comment by Linux-LIVING** [comment]
EVERYTHING IS WORKING   100%  PERFECT.. everything is working 100% perfectly. thank you !!  

i tested on my current machine (where it didint work before)  and now everything is working
i also tested in a freshly installed OS and everything is fine.

 --- tested in:  parrot security os 4.10, debian based,  kernel 5.10.15  (working 100% perfect)

--- tested in: kali linux 2020.4 <debian based> (working 100% perfect)
--- tested in: kali linux 2019.4  <debian based> (working 100% perfect)
--- tested in: ubuntu 20.04 <debian based> (working 100% perfect)
--- tested in: ubuntu 20.04.1 <debian based> (working 100% perfect)
--- tested in: ubuntu 20.04.2 <debian based> (working 100% perfect)
--- tested in: ubuntu 20.10  <debian based> (working 100% perfect)
--- tested in: debian 10.6        <debian based>(working 100% perfect)
--- tested in: debian 10.8 <the current/newest version, released in 6-feb-2021>  (working 100% perfect)
--- tested in:  ubuntu dde(deepin desktop enviroment)  (working 100% perfect)
    ^ all of the above were tested in physical hardware

** i will coninue using linux-wifi-hotspot and testing,  in both physical hardware and virtual machines.... if there is a problem i will make a mention of it here, and in a bug report...  if everything works well  and no issues are encountered there will be no posts from me here..

thank you
