### ISSUE TITLE
Can't Use Wifi And Create_ap At Same time

### ISSUE THREAD

**Issue by inegan** [lakinduakash/linux-wifi-hotspot#146]
**Describe the bug**

**To Reproduce**
1. it's problem from create_ap not the tool it self
2. When i use WI Hotspot Gui Or Create AP This Happen
https://imgur.com/2C6Xgvj

The Wifi Networks not show up and my wireless interface get disabled. yes hotspot work fine and i can connect and use it
but on my pc i can't use wifi network anymore

i'm opening this to know if this normal or not?

i'm able to Fix the issue when i do this steps : 
sudo gedit /etc/NetworkManager/NetworkManager.conf
delete this:
[keyfile]
unmanaged-devices=interface-name:wlx00c0ca847ab3
sudo service network-manager restart

or just kill create_ap

**Desktop (please complete the following information):**
 - OS: Ubuntu 18 .04
 - Zorin 15 

**Additional context**
if there any way or update to this project to make wifi and hotspot work at same time it will be really great ! :+1: 

Thanks for hard work!

**Comment by lakinduakash** [comment]
This is not normal. This is intended to connect wifi and make a hotspot same time. There might be an issue with the network manager itself. 

Does this happen every time you start the hotspot?

**Comment by inegan** [comment]
> This is not normal. This is intended to connect wifi and make a hotspot same time. There might be an issue with the network manager itself.
> 
> Does this happen every time you start the hotspot?

Yes every time i try it happen

**Comment by inegan** [comment]
also i install the OS on my 2 pc and same issue present
i guess it's something related to my WIFI USB? ( Tp link w722n V2 )

**Comment by inegan** [comment]
after make some tests i found the tool
automatic make this line at " /etc/NetworkManager/NetworkManager.conf "

[keyfile]
unmanaged-devices=interface-name:wlx00c0ca847ab3

if i removed this line, The Network & Hotspot work at same time fine

but when i reboot the tool. it's automatic create this line again which lead wifi not show again

is there way to make the tool not make this line?

**Comment by ouuan** [comment]
> after make some tests i found the tool
> automatic make this line at " /etc/NetworkManager/NetworkManager.conf "
> 
> [keyfile]
> unmanaged-devices=interface-name:wlx00c0ca847ab3
> 
> if i removed this line, The Network & Hotspot work at same time fine
> 
> but when i reboot the tool. it's automatic create this line again which lead wifi not show again
> 
> is there way to make the tool not make this line?

It was added in https://github.com/oblique/create_ap/commit/fb266ab79829fdbc896874a7e10734fb21c667f5. But there was no commit message to explain this and [it's in the initial commit](https://github.com/oblique/create_ap/commit/01abb28e2c94b59f39b2c54f9b5d2f7ab189c570#diff-f034d777c0567d296b34aa4a876d00600a75cffd1cd38191e46d562ce18a2d73R155-R160).

**Comment by sigmaSd** [comment]
I think this issue can be closed because the create_ap script in this repo does not create that entry (it does not pass --fix-unmanaged)
