### ISSUE TITLE
Kali repo

### ISSUE THREAD

**Issue by d0lla1976** [lakinduakash/linux-wifi-hotspot#147]
**Describe the bug**

When adding your ppa: to debian/kali repos It keeps telling me that it has not been signed.. Is there anything else i can do or just update manually?

sudo add-apt-repository ppa:lakinduakash/lwh

Err:7 http://ppa.launchpad.net/lakinduakash/lwh/ubuntu hirsute Release                       
  404  Not Found [IP: 91.189.95.85 80]
E: The repository 'http://ppa.launchpad.net/lakinduakash/lwh/ubuntu hirsute Release' does not have a Release file.

**Comment by lakinduakash** [comment]
You can always install Debian file in GitHub release section.
I added `hirsute` release.

**Comment by d0lla1976** [comment]
Ok..Thanks brother...
