### ISSUE TITLE
AP not visible from any device, but create_ap has no errors

### ISSUE THREAD

**Issue by nichite** [lakinduakash/linux-wifi-hotspot#157]
**Describe the bug**
Just getting started with `linux-wifi-hotspot`, I'm running an RPi4 with Ubuntu 20.04.2.

When creating the AP, the command seems to run successfully:

```
Config dir: /tmp/create_ap.wlan0.conf.Ad2YQ7eD
PID: 9910
Network Manager found, set wlan0 as unmanaged device... DONE
Sharing Internet using method: nat
hostapd command-line interface: hostapd_cli -p /tmp/create_ap.wlan0.conf.Ad2YQ7eD/hostapd_ctrl
Configuration file: /tmp/create_ap.wlan0.conf.Ad2YQ7eD/hostapd.conf
wlan0: interface state UNINITIALIZED->HT_SCAN
20/40 MHz operation not permitted on channel pri=1 sec=5 based on overlapping BSSes
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr dc:a6:32:e7:8f:0b and ssid "highlands_nichite"
wlan0: interface state HT_SCAN->ENABLED
wlan0: AP-ENABLED 
```

But the AP itself can't be found from any of the device I'm trying to connect to it (e.g. phone, laptop). Sometimes soon after starting the AP, I see it in the list of networks for a few seconds, then it disappears. Manually entering the SSID on my laptop and attempting to connect doesn't work.

I read in similar issues to try using the `--ieee80211n`, `--ieee80211ac` flags, neither of those changed this behavior for me.

**To Reproduce**
I'm running `create_ap` using this command:

`create_ap --config /etc/create_ap.conf`

Here's the contents of the `create_ap.conf` file:

```
CHANNEL=default
GATEWAY=10.0.0.1
WPA_VERSION=2
ETC_HOSTS=0
DHCP_DNS=gateway
NO_DNS=1
NO_DNSMASQ=0
HIDDEN=0
MAC_FILTER=0
MAC_FILTER_ACCEPT=/etc/hostapd/hostapd.accept
ISOLATE_CLIENTS=0
SHARE_METHOD=nat
IEEE80211N=0
IEEE80211AC=0
HT_CAPAB=[HT40+]
VHT_CAPAB=
DRIVER=nl80211
NO_VIRT=0
COUNTRY=
FREQ_BAND=2.4
NEW_MACADDR=
DAEMONIZE=0
NO_HAVEGED=0
WIFI_IFACE=wlan0
INTERNET_IFACE=eth0
SSID=MyAccessPoint
PASSPHRASE=foobar
USE_PSK=0
```

**Expected behavior**
I should be able to see `MyAccessPoint` on the list of networks on my phone/laptop.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.2

**Comment by nichite** [comment]
Realized I had the wrong project open. Oops.

**Comment by nichite** [comment]
For posterity, the cause of this issue was a bad broadcom firmware version on my Pi. See this discussion: https://github.com/iiab/iiab/issues/823#issuecomment-662285202

I resolved it using the following commands from the post:

```
# Download old firmware (note I don't use the one linked in the github issue above, but their sha256sum's are identical: d583a5a0e1e523dba24f07771d99dd281d540d3675c5d3bcd9b991c6e97fa745)
wget https://github.com/RPi-Distro/firmware-nonfree/raw/cd4184e8c484790ef211ee989e37d6319ba4bc78/brcm/brcmfmac43455-sdio.bin
sudo cp brcmfmac43455-sdio.bin /lib/firmware/brcm/
sudo reboot
```

**Comment by lakinduakash** [comment]
Thanks for the comment. I will add this to README.md
