### ISSUE TITLE
not able to install wifihotspot application. I am facing this problem while running the programs

### ISSUE THREAD

**Issue by pratham11148** [lakinduakash/linux-wifi-hotspot#162]
![VirtualBox_Kali 2020 x64 Customized by zSecurity v1 3_24_05_2021_21_58_20](https://user-images.githubusercontent.com/84732405/119377879-3b14a300-bcdb-11eb-9e62-d39cbe224862.png)
root@kali:~/linux-wifi-hotspot/linux-wifi-hotspot# make
mkdir -p build
Run 'sudo make install' for installation.
Run 'sudo make uninstall' for uninstallation.
cd src && make
make[1]: Entering directory '/root/linux-wifi-hotspot/linux-wifi-hotspot/src'
Package gio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gio-2.0' found
ui/glade/wifih.gresource.xml --target=ui/resources.c --sourcedir=ui/glade --generate-source
make[1]: execvp: ui/glade/wifih.gresource.xml: Permission denied
make[1]: *** [Makefile:31: resources.c] Error 127
make[1]: Leaving directory '/root/linux-wifi-hotspot/linux-wifi-hotspot/src'
make: *** [Makefile:5: all] Error 2
root@kali:~/linux-wifi-hotspot/linux-wifi-hotspot# 
root@kali:~/linux-wifi-hotspot/linux-wifi-hotspot# #install
root@kali:~/linux-wifi-hotspot/linux-wifi-hotspot# sudo make install
Installing...
cd src && make install
make[1]: Entering directory '/root/linux-wifi-hotspot/linux-wifi-hotspot/src'
make[1]: *** No rule to make target '../build/wihotspot-gui', needed by 'install'.  Stop.
make[1]: Leaving directory '/root/linux-wifi-hotspot/linux-wifi-hotspot/src'
make: *** [Makefile:9: install] Error 2

**Comment by lakinduakash** [comment]
Please install the all the required build dependencies before build. Check the README.md

**Comment by pratham11148** [comment]
> Please install the all the required build dependencies before build. Check the README.md

idk how to do it could please guide me ??
