### ISSUE TITLE
App broken after recent Ubuntu 20.04 update

### ISSUE THREAD

**Issue by cccaballero** [lakinduakash/linux-wifi-hotspot#169]
After a recent Ubuntu 20.04 update the app stops working, it creates the hotspot successfully, but after a few seconds the network manager says that connection was lost and the whole wifi stops working until I reboot. I am testing with a wireguard interface (wg0) for sharing a VPN connection with other devices, and it have being working perfectly until my last system update.

#### System info:

OS: Ubuntu Linux 20.04 x86_64
Kernel: 5.8.0-59-generic
DE: GNOME 3.36.8

**Comment by lakinduakash** [comment]
That's working in ubuntu 20.04. If you update the Ubuntu try to uninstall completely and install again.
