### ISSUE TITLE
App is not runnig in Linux Mint 20 Ulyana

### ISSUE THREAD

**Issue by TayyabAsghar** [lakinduakash/linux-wifi-hotspot#171]
**Describe the bug**
I can't run the app after installation. App keeps running `Getting running info...` and `Create hostspots` button is disabled. The `SSID` and `Password` fields does not let you change the default data in those fields. But you can select  `Advance Options`.

**To Reproduce**
1. Download all the dependencies instructed in the README.md.
2. Run the commands for Debian/Ubuntu based Linux.
3. Run the `Wifi Hostspot` from the icon in the apps.

**Expected behavior**
I should be able to change the SSID and Password Field and able to click `Create Hostspot` button to create my hostspot.

**Screenshots**
![error](https://user-images.githubusercontent.com/46403585/124399595-bbe0a900-dd35-11eb-8ba8-ee67d34eac18.png)

**Desktop:**
 - OS:  Linux Mint
 - Version: 20 Ulyana

**Comment by lakinduakash** [comment]
Please select Internet and WiFi interfaces
