### ISSUE TITLE
Cannot install on Ubunutu 18.04 iw version 

### ISSUE THREAD

**Issue by ekrimsk** [lakinduakash/linux-wifi-hotspot#178]
When trying to install I get 
`The following packages have unmet dependencies:
 linux-wifi-hotspot : Depends: iw (>= 5.4)
                      Depends: iproute2 (>= 5.0)
E: Unable to correct problems, you have held broken packages.
`
Trying to upgrade iw with `sudo apt --only-upgrade install iw ` gives me `iw is already the newest version (4.14-0.1).`
Which I think is the latest version of iw supported on Ubuntu 18.04. Is there any way around this without upgrading to 20.04?

**Comment by lakinduakash** [comment]
Sorry for the inconvenience, You can always build the package from the source and install it. Follow the README for the steps. Or you can try uninstalling the `iw` and try to reinstall it with `apt upate`. This package worked for ubuntu 18.04 anyway.
