### ISSUE TITLE
Add a inserted window to show connected devices

### ISSUE THREAD

**Issue by Nexround** [lakinduakash/linux-wifi-hotspot#179]
Thank you for your amazing work! @lakinduakash
When I was using this tool I felt that it would be convenient if we could see a list of connected devices inside the main window. So I would like to contribute this function. I wish I could have your support, thanks!

**Comment by lakinduakash** [comment]
That's cool. UI of the project is built with GTK. `glade` files are used to arrange the UI. Refer to the `src` folder, it has all the files. You can create a new glade file or use an existing one to show the connected list. I think it is better to add a new section like in `advanced` and list the devices connected. You can also refer the issue #49 for the command to get the connected devices.
