### ISSUE TITLE
Add specific clients to the network !!!

### ISSUE THREAD

**Issue by zakariaoussete** [lakinduakash/linux-wifi-hotspot#180]
I think this can be really helpful for a lot of linux users, like creating a host file and the only people can join this AP is the clients inside the host file is there a way to do that like for an open network ?!!!

**Comment by lakinduakash** [comment]
You can use mac filter for this. Add the allowed user's mac addresses to the `Mac Filter` field

**Comment by LINUX-LIVING** [comment]
Yes,  you can use the Mac filter in linux wifi Hotspot.. I use it all the
time

Greetings.. from linux living.
I'm your fan lakinduakash
