### ISSUE TITLE
Alternative Wording For `You must run it as root.`

### ISSUE THREAD

**Issue by enikoli** [lakinduakash/linux-wifi-hotspot#181]
**Is your feature request related to a problem? Please describe.**
When `create_ap` is run as an unprivileged user, the programs gives an error that reads `You must run it as root.` The program referring to itself as “it” in a one-line output  is an unusual wording compared to other CLI programs.

**Describe the solution you'd like**
`Please run this as root`
`create_ap must be run as root`

**Describe alternatives you've considered**
Not changing this.

**Comment by lakinduakash** [comment]
Done! Thanks
