### ISSUE TITLE
No Internet Connection (Manjaro)

### ISSUE THREAD

**Issue by jp-san-gabriel** [lakinduakash/linux-wifi-hotspot#183]
Hi,

I installed it on Manjaro XFCE from AUR. My laptop was able to connect as a wifi client and while being access point at the same time. However, devices connected to the access point cannot access the internet, while the laptop itself has internet access.

**Comment by lakinduakash** [comment]
Can you try it from the command line (`create_ap`) with bridge connection?

**Comment by bagusyusup** [comment]
hi, i have the same problem on pop os

**Comment by jko-nic** [comment]
This problem persist in latest version (4.4.0), but also on 4.3.3 and 4.3.2, on up-to-date Manjaro. If running with `sudo create_ap wlo1 enp55s0u1u4 'mynetwork' 'mypassword' --freq-band 2.4`, it says:
```
Config dir: /tmp/create_ap.wlo1.conf.s0JKkrNZ
PID: 137596
Network Manager found, set ap0 as unmanaged device... DONE
Creating a virtual WiFi interface... ap0 created.
Sharing Internet using method: nat

dnsmasq: cannot read /tmp/create_ap.wlo1.conf.s0JKkrNZ/dnsmasq.conf: Permission denied

Doing cleanup.. done
```

Both interfaces exists. I would be very grateful if this can be fixed in some way. Thank you :)

**Comment by testman42** [comment]
can confirm, the above command made it work for me as well. Thank you for sharing the solution :+1:
