### ISSUE TITLE
port forwarding - server run on gateway/hotspot

### ISSUE THREAD

**Issue by danjenson** [lakinduakash/linux-wifi-hotspot#195]
I am running linux-wifi-hotspot on a raspberry pi, which I have converted into a router, routing traffic from an external network connected via a usb wifi antenna to a local area network created by this hotspot. To make it easy to select the external network, I have created a simple server that serves a web UI for selecting a wifi nework. I'd like to host this server on the same raspberry pi that is hosting the hotspot, so someone can connect to the LAN then navigate to the web UI to select the external wifi network to connect to. However, I'm not sure if this is possible, since I kind of need the same computer hosting the gateway to connect to that network, so my external wifi selector server has a LAN IP address.

Is this possible currently? It would be nice to be able to just "login" to the gateway address, i.e. run the server on localhost and then log into the webui with <gateway_ip>:8000, i.e. 192.168.12.1:8000. So the gateway forwards traffic to local/host ports/services.

**Comment by lakinduakash** [comment]
I think this is possible with some extra tools. The tool itself cannot select which WiFi network is already connected, it can select the WiFi interface only. Selecting which WiFi AP is connected to the WiFi card should be done via separate tool/command (you may want to search command that able to select wifi network and connect to it). You can run that command via WebUI and restart the hotspot ( it may be work without restarting - need to check). It just need to initially have the hotspot from RaspberryPi and run the web server on it. Then when you need to run the series of command from the web sever - select wifi network and connect to it then restart the hotspot etc. Hope it helps.
