### ISSUE TITLE
Uptate

### ISSUE THREAD

**Issue by manishjvora** [lakinduakash/linux-wifi-hotspot#211]
I am unable to receive update from mintUpdate (update manager) even when repo is there on PPA

**Comment by lakinduakash** [comment]
What is your OS?

**Comment by manishjvora** [comment]
LinuxMint

**Comment by manishjvora** [comment]
LinuxMint

**Comment by lakinduakash** [comment]
Actually it is only for ubuntu. You can manually download the deb file from release. Hope to integrate it with Mint in future.
