### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by OliveS9** [lakinduakash/linux-wifi-hotspot#216]
Could anyone please help with fixing the following import error when running wifiutil_linux.py? Thanks a lot.

    "280         ifaces = []
--> 281         for f in sorted(os.listdir(CTRL_IFACE_DIR)):
    282             sock_file = '/'.join([CTRL_IFACE_DIR, f])
    283             mode = os.stat(sock_file).st_mode

FileNotFoundError: [Errno 2] No such file or directory: '/var/run/wpa_supplicant'"

**Comment by lakinduakash** [comment]
Is this relevant to this repository?
