### ISSUE TITLE
Wifihotspot issue

### ISSUE THREAD

**Issue by Cybersecurity6082** [lakinduakash/linux-wifi-hotspot#222]
When we clone the tool then install make file 
When we install make file this error is occured
![IMG20220115151106](https://user-images.githubusercontent.com/97800355/149630072-33410772-8bdb-4d46-bcf5-8b63a2fdef5b.jpg)

**Comment by lakinduakash** [comment]
Please read the steps carefully again. You need to run `make` first and then run `sudo make install`

**Comment by Cybersecurity6082** [comment]
How can we run make

**Comment by Cybersecurity6082** [comment]
Plzz tell ma the code to run make

**Comment by lakinduakash** [comment]
Just run type `make` and hit enter.

**Comment by Cybersecurity6082** [comment]
Only we type make and then enter??

**Comment by lakinduakash** [comment]
Yes

**Comment by Cybersecurity6082** [comment]
When we type make and then we enter this error is showing
![Uploading 16423483145586357047737291827311.jpg…]()
What can i do

**Comment by Cybersecurity6082** [comment]
When we type make and then we enter this error is showing what can i do to solve this error
![IMG20220115151106](https://user-images.githubusercontent.com/97800355/149667347-dd559e1a-e834-44ed-9538-e4f0b0b7df4a.jpg)

**Comment by lakinduakash** [comment]
Why don't you understand that I'm saying just type `make` not `make install`. You are typing wrong commands. Please read the README.md and it has listed down all procedures and commands

**Comment by lakinduakash** [comment]
Did you get it?

**Comment by Cybersecurity6082** [comment]
Sorry i post the wrong pic

**Comment by lakinduakash** [comment]
What is the error then? Make sure to install all the dependencies first listed in README

**Comment by Cybersecurity6082** [comment]
When we type make and then press enter this error is showing
![16423522753748496573079816639786](https://user-images.githubusercontent.com/97800355/149669807-a8ab1cfc-bc63-4e7f-bb07-17b02bc73060.jpg)

**Comment by lakinduakash** [comment]
I think there's some permission issues in your directory. Make sure to have write permission inside the cloned directory. May be you can start over by cloning again the repository.

**Comment by Cybersecurity6082** [comment]
Wifihotspot is installed 
Thank you for your efforts and guidance

**Comment by Newone842** [comment]
I have follow every instruction posted concerning the installation and unfortunately  for me, I still cannot get this installed or operational for some reason I am missing something not even sure its installed yet. It would be nice to have a clear explanation as to what I need do in order to get this gui up and running properly. I am running a Kali build most recent one. Thanks for the help in advance.
