### ISSUE TITLE
cannot find package on Linux mint 20.3 (Based on Ubuntu)

### ISSUE THREAD

**Issue by Avinashachu007** [lakinduakash/linux-wifi-hotspot#228]
**Describe the bug**
I cannot install the linux-wifi-hotspot package even after adding the repo.

**To Reproduce**
1. Open terminal
2. Add Repo ` sudo add-apt-repository ppa:lakinduakash/lwh`
3. Execute `sudo apt install linux-wifi-hotspot`
4. See error `E: Unable to locate package linux-wifi-hotspot`

**Desktop (please complete the following information):**
OS: Linux Mint 20.3 x86_64 
Kernel: 5.4.0-96-generic
DE: Cinnamon

**Comment by lakinduakash** [comment]
Sorry, this is currently available for ubuntu and arch as packages. You can download the Debian package from release or built yourself using the guid. I will try to add to other OS repos as well.
