### ISSUE TITLE
FREQ_BAND in configuration file is invalid

### ISSUE THREAD

**Issue by cnjhb** [lakinduakash/linux-wifi-hotspot#236]
**Describe the bug**
FREQ_BAND in configuration file is invalid

**To Reproduce**
1. Set FREQ_BAND in the configuration file to 2.4
2. use that configuration file
3. But still using band 5

**Expected behavior**
in the config file
set 2.4 -> use 2.4
set 5 -> use 5

**Desktop (please complete the following information):**
 - OS: [archlinux]
 - Version [null]

**Comment by lakinduakash** [comment]
Thanks, btw this worked until then and no issue occurred. Did you test the behavior after PR?

**Comment by cnjhb** [comment]
i tested,it works.

**Comment by cnjhb** [comment]
FREQ_BAND_SET is not set when reading FREQ_BAND from a configuration file, which will cause the band to be automatically selected.
