### ISSUE TITLE
Why restricts 5Ghz channels to <=36.

### ISSUE THREAD

**Issue by haoyun** [lakinduakash/linux-wifi-hotspot#24]
**Is your feature request related to a problem? Please describe.**
There are more [5 GHz channels](https://www.wikiwand.com/en/List_of_WLAN_channels#/5_GHz_(802.11a/h/j/n/ac/ax)) available, which are not only legal but also supported by network adapters. For example, my card support
```
                        * 5745 MHz [149] (22.0 dBm)
                        * 5765 MHz [153] (22.0 dBm)
                        * 5785 MHz [157] (22.0 dBm)
                        * 5805 MHz [161] (22.0 dBm)
                        * 5825 MHz [165] (22.0 dBm)
```
But https://github.com/lakinduakash/linux-wifi-hotspot/blob/613af3b37e3b606a8336a5351b5c3196633c7f1c/src/ui/ui.c#L299 requires the channel number to be no more than 36.

**Describe the solution you'd like**
change 36 to a large number, e.g, 173, or make it region dependent.

**Comment by lakinduakash** [comment]
Yes. I also recently faced that problem. I will change that. Thank you. :)
