### ISSUE TITLE
create_ap inside systemd service: wlan0 is not a WiFi interface

### ISSUE THREAD

**Issue by onny** [lakinduakash/linux-wifi-hotspot#243]
**Describe the bug**
I'm currently trying to make a module of linux-wifi-hotspot for NixOS https://github.com/NixOS/nixpkgs/pull/168510

The systemd service launches `create_ap` with `--config` parameter and following config file:
``` 
INTERNET_IFACE=enp0s25
PASSPHRASE=12345678
SSID=onnys hotspot
WIFI_IFACE=wlan0
```

This command does work if I run it from my shell. Inside the systemd service it fails with `'wlan0' is not a WiFi interface`.

I already did some debugging and it looks like the function `is_wifi_interface` gets only `0` passed as an argument for the interface name. Not sure why, maybe someone has an idea?

Regards
Jonas

**Comment by lakinduakash** [comment]
Hi,
does it start at startup or same happen in anytime you start the service via systemd?

**Comment by onny** [comment]
Oh sorry it was a missing dependency. I guess the NixOS service for your create_ap script should work :) I also wrote a blog post about it: https://blog.project-insanity.org/2022/04/14/easily-configure-a-wifi-hotspot-on-nixos/

Thank you for this program :)

**Comment by lakinduakash** [comment]
That's great you help to spread this to the community

**Comment by tminhvu** [comment]
Ran into this same issue but I already installed every dependency. No idea what to do now.
