### ISSUE TITLE
No package 'gtk+-3.0' found in Parrot OS distro

### ISSUE THREAD

**Issue by Aaron-Ochieng** [lakinduakash/linux-wifi-hotspot#252]
I cannot install the software on the  newer release of parrot  5...

make
mkdir -p build
Run 'sudo make install' for installation.
Run 'sudo make uninstall' for uninstallation.
cd src && make
make[1]: Entering directory '/home/aaron/linux-wifi-hotspot/src'
/usr/bin/glib-compile-resources ui/glade/wifih.gresource.xml --target=ui/resources.c --sourcedir=ui/glade --generate-source
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
make[2]: Entering directory '/home/aaron/linux-wifi-hotspot/src'
gcc -c -o ../build/main.o ui/main.c `pkg-config --cflags gtk+-3.0`
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
In file included from ui/main.c:28:
ui/ui.h:34:10: fatal error: gtk/gtk.h: No such file or directory
   34 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:35: ../build/main.o] Error 1
make[2]: Leaving directory '/home/aaron/linux-wifi-hotspot/src'
make[1]: *** [Makefile:32: resources.c] Error 2
make[1]: Leaving directory '/home/aaron/linux-wifi-hotspot/src'
make: *** [Makefile:5: all] Error 2

**Comment by lakinduakash** [comment]
Did you install `libgtk-3-dev`?

**Comment by Aaron-Ochieng** [comment]
Apparently it's somehow impossible to install libgtk-3-dev. On 26 May 2022 12:10 pm, Lakindu Akash ***@***.***> wrote:
Did you install libgtk-3-dev?
