### ISSUE TITLE
Accept 'additional hosts file' option from create_ap.conf

### ISSUE THREAD

**Issue by brentdewe** [lakinduakash/linux-wifi-hotspot#253]
**Is your feature request related to a problem? Please describe.**
When starting `create_ap` from the command line, I can specify an additional hosts file with the argument `-e /etc/hosts-ap`, but it is not possible to specify this in a config file passed with `--config`. I tried to set `ADDN_HOSTS=/etc/hosts-ap` in the config based on the `create_ap` code, but I get the warning
```shell
WARN: Unrecognized configuration entry ADDN_HOSTS
```

**Describe the solution you'd like**
I want to be able to pass `ADDN_HOSTS=/etc/hosts-ap` through a config file when starting `create_ap`.

**Describe alternatives you've considered**
When I add `ADDN_HOSTS` to `CONFIG_OPTS` in [create_ap:660](https://github.com/lakinduakash/linux-wifi-hotspot/blob/177c36c9e09409c58b6019b6ea80fe9edb5eb879/src/scripts/create_ap#L660), it reads the option and passes it to dnsmasq as expected.
At the moment I have to override the systemd service from which it runs to add the `-e /etc/hosts-ap` argument.

**Additional context**
I run Arch Linux and installed `linux-wifi-hotspot` from the AUR. I want to use the systemd service which basically  runs 
```shell
create_ap --config /etc/create_ap.conf
```
at boot time.

**Comment by sigmaSd** [comment]
The option needs to be added in config opts, I opened a pr to add it, if you're missing other opts feel free to add them there.
