### ISSUE TITLE
Hotspot doesn't start on pi 4B

### ISSUE THREAD

**Issue by abraha2** [lakinduakash/linux-wifi-hotspot#255]
**Describe the bug**
  I downloaded this package on an ABSOLUTELY fresh install of the Raspberry Pi OS, running on the Raspberry Pi 4B. The app installed, and opened, but when I clicked on the  "Create hotspot" button, it just wouldn't start.
  The window didn't crash, and it gave me no error message. It simply said "Getting running info," and then "not running."

**To Reproduce**
1. download app on the Raspberry Pi 4B, with the latest Raspberry Pi OS. (as of June 27)
2. start app
3. click "Create hotspot."

**Expected behavior**
When you click the "Create hotspot" button, the loading bar should appear for a few milliseconds. the text under it says: "Getting running info," and then it appears to simply give up. the loading bar disappears, and the text at the bottom left says "Not running."

**Screenshots**
I could not provide a screenshot, because there is no visual evidence of an error.

**Desktop (please complete the following information):**
 - OS: the official Raspberry Pi OS running on the Pi model 4B
 - Version (found using the command "uname -srm")Linux 5.15.32-v7l+ armv7l

**Additional context**
  I tried the same thing, except using a Raspberry Pi 3B+, and it worked pefectly!
The hotspot started, and it supplied my phone with internet, but I never tried connecting to a wifi network at the same time, instead, the Raspberry Pi 3B+ was connected to an ethernet cable. I still would appreciate your help in fixing the bug, though.

**Comment by Letme** [comment]
Did you install the dependencies as well? Because I noticed that package itself does not have dependencies to all the packages in READme.

**Comment by abraha2** [comment]
Where is a list of dependencies, if one exists.

**Comment by Letme** [comment]
https://github.com/lakinduakash/linux-wifi-hotspot#dependencies

You have below a apt command to install them...

**Comment by abraha2** [comment]
Are you talking about the list of dependencies in the readme.md file?
Because, if you are, then I already double checked that list, making sure all of them were installed.
They were, and it still didn't work.

**Comment by Letme** [comment]
ok. If you run the app from the terminal (wihotspot-gui) you will get some more details about the errors.

(Maybe you did not select Wifi and Internet interfaces?)

**Comment by abraha2** [comment]
I tried running it in the terminal, like you said, and I got this error:

"WARN: brmfmac driver doesn't work properly with virtual interfaces and it can cause kernel panic. For this reason we disallow virtual interfaces for your adapter.
ERROR: Your adapter can not be a station (i.e., be connected) and be an AP at the same time."

Why does it say that, when the app devs clearly stated that that ability was indeed present?
Is it just an "I don't know if I can do this, so I'll say I can't"  sort of circumstance?
Also, what does it mean by "adapter?"
Does it think I have a USB wifi adapter plugged in, or is that what it calls the internal wifi chip?

**Comment by Letme** [comment]
Adapter is just a name, no idea why you would say USB - do you have USB plugged in? Now at least you got the reason - maybe poke around with some settings?

**Comment by Letme** [comment]
(now would be the point where you would share the settings with us so that we can maybe check what you adjusted)

**Comment by abraha2** [comment]
I don't think there are any settings I can adjust 
At least, none that I know of
Also, I do not have a USB wifi adapter plugged in.

**Comment by sigmaSd** [comment]
The warning message explains that your wifi adapter doesn't support virtual interfaces, that's why it can't connect to it and be an ap at the same time

**Comment by abraha2** [comment]
UPDATE:
I finally got the hotspot to start, on the Pi4B. The reason it wouldn't start is that I had this internet source set to wlan0, instead of eth0. However,  I still can't host a hotspot and connect to one, at the same time.

**Comment by abraha2** [comment]
> The warning message explains that your wifi adapter doesn't support virtual interfaces, that's why it can't connect to it and be an ap at the same time

Does this mean that I can't use that function at all?

**Comment by abraha2** [comment]
Is anyone still following this, or is it dead?

**Comment by Letme** [comment]
We are, but kinda you dont have an issue anymore since you started the hotspot...

**Comment by abraha2** [comment]
Ah, I see.
Indeed, the first problem was fixed, but I was trying to connect to a wifi, and create a hotspot at the same time.

**Comment by abraha2** [comment]
Sorry for the misunderstanding.

**Comment by abraha2** [comment]
Can my pi just not do both at once, then?

**Comment by Letme** [comment]
If you still get error from above, then that is what is says:

```
ERROR: Your adapter can not be a station (i.e., be connected) and be an AP at the same time.
```

**Comment by abraha2** [comment]
Allright, then.
I guess I'll stop trying to fix it, since there is no problem.

**Comment by sigmaSd** [comment]
My advice is to just buy a cheap wifi adapter

**Comment by lightmon233** [comment]
> Ah, I see. Indeed, the first problem was fixed, but I was trying to connect to a wifi, and create a hotspot at the same time.
> 
> I am sorry for the misunderstanding.

guy i am facing the same issue as yours hah, might be pi 4b's hardware issue
