### ISSUE TITLE
Format version 

### ISSUE THREAD

**Issue by AgentBlade4** [lakinduakash/linux-wifi-hotspot#259]
**Describe the bug**
Hotspot won’t start up due to error

**To Reproduce**
1. Open `wihotspot`
2. Click “Create hotspot”
3. See error.

**Expected behavior**
Hotspot will start as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/91215067/182236374-17fc0e83-104a-4cfb-995d-077244014bad.jpg)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version Rpi3B Hotspot ver 4.4.0

**Comment by lakinduakash** [comment]
Pleased install all the dependencies before you run. In your case `dnsmasq`
command is not found. Install it fisrt.

**Comment by devheshmati** [comment]
that's work to me thank`s @lakinduakash
