### ISSUE TITLE
5GHz channels

### ISSUE THREAD

**Issue by haoyun** [lakinduakash/linux-wifi-hotspot#26]
This is actually a problem with `create_ap`, but not with `linux-wifi-hotspot`.

`create_ap` only support to set up AP **on the same channel** as the WiFi connection is on. So if the Wifi connection is 5GHz, then the AP has to be on 5GHz, **on the same channel**. Then people usually got errors like
```
Your adapter can not transmit to channel 36, frequency band 5GHz.
```
However there are some different cases when this happens.
1. The user's adapter or driver does not support to set up AP on 5GHz. In this case, I believe that we can do nothing to make things work, other than ask the user to switch to a 2.4GHz WiFi.
2. The user's adapter and driver support 5GHz AP, but can only transmit to channels different from the one that the adapter is already associated to.
 2.1. the adapter or driver does not support multiple channels. We can no nothing.
 2.2. **the adapter and the driver support multiple channels**, e.g., when ` #channels <= 2` instead of ` #channels <= 1`  in the following output
```
$ iw list
----------------------------------------------------------------------------------------------------
...

        valid interface combinations:
                 * #{ managed } <= 1, #{ AP, P2P-client, P2P-GO } <= 1, #{ P2P-device } <= 1,
                   total <= 3, #channels <= 2

...
```

In this case, a hack to `create_ap` can also make things work, see https://github.com/oblique/create_ap/issues/75#issuecomment-497981037.

So I think there are some work to be done so that we can make this app work better.

* parse `iw list` to see if multiple channels is supported. (I am not sure if there are any chipset supporting more than 2 channels)

```
if iw list | grep "#channels <= 2" -q 
then
   echo "DUAL-CHANNEL SUPPORTED";
else
   echo "DUAL-CHANNEL NOT SUPPORTED";
fi
--------------------------------------------------------------------------------
DUAL-CHANNEL SUPPORTED

```

* parse `iw list` to get a list of supported channels. This one has its own importance so that users can select  a channel from a list in the UI, rather than fill in a number.
```
iw list | grep "\* [0-9]* MHz \[[0-9]*\]" | while read l; do [[ $l != *disabled* ]] && [[ $l != *no\ IR* ]] && echo "$l"; done
--------------------------------------------------------------------------------
* 2412 MHz [1] (22.0 dBm)
* 2417 MHz [2] (22.0 dBm)
* 2422 MHz [3] (22.0 dBm)
* 2427 MHz [4] (22.0 dBm)
* 2432 MHz [5] (22.0 dBm)
* 2437 MHz [6] (22.0 dBm)
* 2442 MHz [7] (22.0 dBm)
* 2447 MHz [8] (22.0 dBm)
* 2452 MHz [9] (22.0 dBm)
* 2457 MHz [10] (22.0 dBm)
* 2462 MHz [11] (22.0 dBm)
* 2467 MHz [12] (22.0 dBm)
* 2472 MHz [13] (22.0 dBm)
* 5745 MHz [149] (22.0 dBm)
* 5765 MHz [153] (22.0 dBm)
* 5785 MHz [157] (22.0 dBm)
* 5805 MHz [161] (22.0 dBm)
* 5825 MHz [165] (22.0 dBm)
```

`create_ap` has functions to test if wifi is connected, and if so, the frequency of the connection. Combined with the above info, one can decide easily which channel to use.

**Comment by haoyun** [comment]
BTW, a better replacement of `create_ap` may be [garywill/linux-router](https://github.com/garywill/linux-router).

**Comment by lakinduakash** [comment]
Yes, I knew that issue. My solution was to select the Frequency band explicitly in UI instead of **Auto** if that message appears. I have mentioned it in README.md. If we could catch that error message and try to switch the frequency band and start automatically would be better.

Replacement to the existing script may require more changes in UI. We can try out on a different branch

**Comment by haoyun** [comment]
Agree. Actually I was working on this. But due to my very limited knowledge of programming, I am quite slow. I‘ve made a  combobox that can show all available channels. I will make a pull request when I finish the work.
