### ISSUE TITLE
/usr/bin/create_ap: line 1778: iptables: command not found

### ISSUE THREAD

**Issue by AndreiCherniaev** [lakinduakash/linux-wifi-hotspot#268]
I install deb package but there was error:
/usr/bin/create_ap: line 1778: iptables: command not found

I do
`sudo apt-get install iptables`

And now hotspot works! I use Xubuntu, uname -a
Linux A
 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
my hardware is Aspire 3 (A315-21-68MZ).

**May be contributor should add iptables to dependencies?**

![hot](https://user-images.githubusercontent.com/27889022/187803525-86ff312e-fd64-4b4f-8add-1910215d44bd.png)

**Comment by lakinduakash** [comment]
`iptables` is already added as a dependency for the deb package.
