### ISSUE TITLE
WiFi Interfaces Can't Be Detected Without Root on Debian

### ISSUE THREAD

**Issue by windowz414** [lakinduakash/linux-wifi-hotspot#272]
**Describe the bug**
As Wihotspot runs as regular user, it works all fine on distros that don't separate PATH entries from root and regular user and instead asks for root when such app is run through a policy (such as Ubuntu, Arch). However, when it comes to Debian itself, since the PATH locations are separated and user can't see root's PATH utilities, `wihotspot` needs to be run as root in order to work properly.

**To Reproduce**
1. Run `wihotspot` either from Terminal or using "Wifi Hotspot" launcher entry as user (without `sudo`).
2. See if "Wifi interface" entry is unavailable to be used.

**Expected behavior**
Able to choose WiFi interface and enable hotspot.

**Screenshots**
![image](https://user-images.githubusercontent.com/39265461/192433499-658f6fe6-0c4f-4c97-b527-c5896b47079f.png)
> If you look closely, you can see "Wifi hotspot" list is empty and can't be used.

**Desktop (please complete the following information):**
 - OS: Pardus GNU/Linux, based on Debian
 - Version: 21 (yirmibir), 21.3 "Dolunay"

**Additional context**
From my observations, using this command makes it work on Terminal but not when the launcher entry is modified to run it or when it's run in desktop-specific "Run a Command" box (usually invoked with Alt+F2);
```
pkexec --user root /usr/bin/sh -c "env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/bin/wihotspot"
```

> I think there should be an implementation that does what this one does. Maybe take advantage from desktop-specific su libraries?

Also, after a while from running the app, I see this log on console, which is also why I recommended running this app as root at least on Debian and distros based on it;
```
sh: 1: iw: not found
```

When running `which iw` on user console, it's not there.
```
stella@kobayashiai:~$ which iw
stella@kobayashiai:~$
```

However, when I look for it as root, means running `sudo which iw`, it IS there, right under `/usr/sbin`, which is the path for executables only `root` is supposed to access;
```
stella@kobayashiai:~$ sudo which iw
[sudo] password for stella: 
/usr/sbin/iw
```

**Comment by lakinduakash** [comment]
Check users $PATH variable. It may not contain the path for `iw`. Update the path and then it will work

**Comment by windowz414** [comment]
> However, when it comes to Debian itself, since the PATH locations are separated and user can't see root's PATH utilities,

As I stated at the very beginning, Debian separates root and regular user apps as a layer of security. Adding root's executables location to user's PATH might cause heavy breakages and security holes; let alone it being really hacky.

That's the reason why I requested that this utility would request root at start rather than outright disqualifying vanilla Debian installs.

**Comment by simonhammes** [comment]
I just ran into this issue (Debian 11). 

Maybe this can be documented in the README (either running `wihotspot` as root **or** making sure `iw` is accessible by the current user)?

However, https://superuser.com/a/595819 recommends against adding `/usr/sbin` to `$PATH` (as @windowz414 previously stated).

**Comment by windowz414** [comment]
> I just ran into this issue (Debian 11).
> 
> Maybe this can be documented in the README (either running `wihotspot` as root **or** making sure `iw` is accessible by the current user)?
> 
> However, https://superuser.com/a/595819 recommends against adding `/usr/sbin` to `$PATH` (as @windowz414 previously stated).

@simonhammes the developer doesn't seem to care about such case at all (I think they never tinkered with Debian?), so we need to ensure people find this issue and raise it up so the developer will be pushed to implement it instead. Pretty sure they would ignore the PRs that would open towards this so...

**Comment by asdhio-github** [comment]
Hi, this solution works (tested on Debian and OpenSUSE):

https://github.com/lakinduakash/linux-wifi-hotspot/issues/319#issuecomment-1588599004
