### ISSUE TITLE
Gateway option in the GUI tool passes wrong argument

### ISSUE THREAD

**Issue by ToxicMushroom** [lakinduakash/linux-wifi-hotspot#273]
**Describe the bug**
The gateway option in the wihotspot-gui passes --gateway to create_ap, this is not an existing option and should probably be -g.

**To Reproduce**
1. Start a hotspot with wihotspot-gui with a custom gateway
2. See error in logs

**Expected behavior**
Gateway option is passed correctly with -g <gateway>

**Screenshots**
![image](https://user-images.githubusercontent.com/32853531/192741764-68d0ba96-f516-4f60-a9b5-6a708973f0d0.png)

**Desktop (please complete the following information):**
 - OS: Arch 
 - Version 5.19.11-arch1-1

**Additional context**
N/A

**Comment by floholz** [comment]
Indeed, it seems that the wrong option '--gateway' is passed from the gui.
The correct option would be '-g'.

The corresponding code can be found here: 
https://github.com/lakinduakash/linux-wifi-hotspot/blob/dd3c72ef4a5e9682ad3a18df3544dac4ec372a1a/src/ui/h_prop.c#L145
