### ISSUE TITLE
Please Add Repository For  Ubuntu 22.10

### ISSUE THREAD

**Issue by aliraza5490** [lakinduakash/linux-wifi-hotspot#280]
**Is your feature request related to a problem? Please describe.**
```
E: The repository 'https://ppa.launchpadcontent.net/lakinduakash/lwh/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Describe the solution you'd like**
Please add the repository for the kinetic kudu release of ubuntu (ubuntu 22.10).

**Describe alternatives you've considered**

**Additional context**

**Comment by lakinduakash** [comment]
I'll add it asap. I lost the GPG keys for the package

**Comment by kocoman2** [comment]
can you remove the # For ubuntu only
sudo add-apt-repository ppa:lakinduakash/lwh
sudo apt install linux-wifi-hotspot
from the main readme/site?  its confusing thx

**Comment by lakinduakash** [comment]
Add a note until I fix, thanks
