### ISSUE TITLE
Netgear WNDA3200 USB Adapter cannot broadcast 5Ghz (but can)

### ISSUE THREAD

**Issue by knuxyl** [lakinduakash/linux-wifi-hotspot#288]
System
Radxa Rock Pi 4B+ (Arm SBC / RK3399)
Netgear WNDA3200 USB Adapter (Atheros AR9002U-2NX) (Atheros AR7010 + Atheros AR9280)
Debain Sid (mainline from https://sd-card-images.johang.se/boards.html)

Bug
iw list shows I can ransmit on every channel available on both 2.4GHz and 5GHz. The onboard wifi, a broadcom chip, shows I cannot transmit on any 5GHz channel. I select the USB adapter in the gui and try to start hotspot and it says
`ERROR: Your adapter can not transmit to channel 36, frequency band 5GHz.`
The 2.4GHz broadcast works fine.

The adapter is listed here
http://en.techinfodepot.shoutwiki.com/wiki/Netgear_WNDA3200

**Comment by uxdiin** [comment]
have you change the channel in advanced options?

**Comment by knuxyl** [comment]
Yes I tried almost every channel that is permissible in USA. I gave up and am done messing with it though, so this can be closed.
