### ISSUE TITLE
unable to on hotspot

### ISSUE THREAD

**Issue by sathya945** [lakinduakash/linux-wifi-hotspot#30]
ERROR: Failed to initialize lock
Command not found or exited with error status

when i press create hotspot this is what i get as output on my terminal

**Comment by lakinduakash** [comment]
Can you provide more details on that?
What is your os and version?
Are you sure every dependency have installed which are mentioned?

**Comment by xuiqzy** [comment]
For me when running `wihotspot` and clicking create hotspot the error is 
```create_ap wlp2s0 wlp2s0 Hotspot hotspotpassword --mkconfig /home/xuiqzy/.wh.config 
Config options written to '/home/xuiqzy/.wh.config'
ERROR: Failed to initialize lock
Command not found or exited with error status
```

When running cli command `sudo create_ap` the error is `ERROR: Failed to initialize lock`

Installed all dependencies, Arch Linux latest version

**Comment by xuiqzy** [comment]
I found the error, it fails when first executing without root permissions and then with root permissions.
The lock file still exists and somehow can't be overridden.
Relevant code should be here: https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/src/scripts/create_ap#L124

**Comment by lakinduakash** [comment]
I think this issue occurs in the Arch Linux.
@xuiqzy Script should always run as root. 
If you run the script as the root user, no issue occurred?

**Comment by xuiqzy** [comment]
If I first run it as normal user and then as root, the issue still occurs and it's hard to figure out how to fix it.
Imo, the script should not create a lockfile if it is run as normal user and just print that it needs to be run as root and exit.

**Comment by lakinduakash** [comment]
I use `pkexec` to gain root access if `wihotspot` run as a normal user. It prompts window to enter the root password. Can you check `pkexec` command available in your system?

**Comment by xuiqzy** [comment]
`pkexec` is available and working when executing manually

**Comment by lakinduakash** [comment]
Can you delete all the lock files manually (If there) and then try to reproduce? I have added a check for root before initializing the lock file.
