### ISSUE TITLE
Command to print out status to different/SSH terminal

### ISSUE THREAD

**Issue by basedBSD** [lakinduakash/linux-wifi-hotspot#301]
I'd love a feature that would let me check status through SSH, I can't find anything about this so I assume it's not possible atm.

Maybe an option to save status info (everything the program would tell me to a different, local terminal) in a file through a command, so I can log in and read it.

**Comment by lakinduakash** [comment]
You can use `create_ap --list-running`.  For more help type `create_ap -h`
