### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by SMScep** [lakinduakash/linux-wifi-hotspot#304]
Hi, whenever I hit create the program will load and some text will appear at the bottom but then it will say not running and the process will stop. This happens no matter what settings I have put for my network. Any advice would be greatly appreciated thanks.

 - OS: Ubuntu
 - Version: 22.04.2
 - My computer: Asus ROG Strix G513IE-HN046W
 - Wifi Adapter: MediaTek Wi-Fi 6 MT7921 Wireless LAN Card (As far as I know)

Please let me know if any additional info is needed or would be helpful, thanks.

**Comment by NightGenji** [comment]
Same problem on Lenovo ideapad 100-15iBy

**Comment by Lyton505** [comment]
Hi, please run the following series of commands

```
sudo apt install apparmor-utils
sudo aa-complain -d /etc/apparmor.d/ dnsmasq 
```

Please let me know if it starts running
