### ISSUE TITLE
Not running at all

### ISSUE THREAD

**Issue by Lyton505** [lakinduakash/linux-wifi-hotspot#305]
I am trying to create a hotspot but it runs and says "not running"

1. Go to 'Wifi Hotspot'
2. Click on 'Create Hotspot'

 - OS: Pop_OS! 22.04

Running it from the terminal gives the following output:

```
pkexec --user root create_ap wlan1 wwan0 'NoClobber' 'password1234' --mkconfig /etc/create_ap.conf --freq-band 2.4 -c 10 
Config options written to '/etc/create_ap.conf'

dnsmasq: cannot read /tmp/create_ap.wlan1.conf.hv8epp2j/dnsmasq.conf: Permission denied
Command not found or exited with error status
```

When I run `cat /tmp/create_ap.wlan1.conf.hv8epp2j/dnsmasq.conf`, the output says there exists no such file

I have been running it normally for the past months. I really don't know why it's misbehaving now.

The command: `journalctl --since "2023-04-05 22:43" --until "2023-04-07 02:00" | grep create_ap | less` gives the following output

```
Apr 05 22:44:24 gecko pkexec[23104]: lyton: Executing command [USER=root] [TTY=unknown] [CWD=/home/lyton] [COMMAND=/usr/bin/create_ap --list-running]
Apr 05 22:44:26 gecko pkexec[23168]: lyton: Executing command [USER=root] [TTY=unknown] [CWD=/home/lyton] [COMMAND=/usr/bin/create_ap wlan1 wwan0 NoClobber freshprince --mkconfig /etc/create_ap.conf --freq-band 2.4 -c 10]
Apr 05 22:44:26 gecko pkexec[23184]: lyton: Executing command [USER=root] [TTY=unknown] [CWD=/home/lyton] [COMMAND=/usr/bin/create_ap --config /etc/create_ap.conf --freq-band 2.4]
Apr 05 22:44:28 gecko audit[23456]: AVC apparmor="DENIED" operation="open" profile="dnsmasq" name="/tmp/create_ap.wlan1.conf.mmtgTY4b/dnsmasq.conf" pid=23456 comm="dnsmasq" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

All along I am running as normal user(as I always do). Running as root doesn't change anything
Thinking that it was a driver issue, I tried using my alfa awus036nha(atheros ar9271 chipset) and I still get the same issue.

**Comment by uWayLu** [comment]
do this  and it works
https://github.com/oblique/create_ap/issues/103#issuecomment-558567466_

**Comment by Lyton505** [comment]
works like a charm. Thanks @uWayLu

**Comment by the-one-irfan** [comment]
Hey there. I just started using linux recently so I have no idea how any of this works. Went through the fix @uWayLu suggested and I was lost. It's the same issue as lyton, I create the hotspot and run but it says not running. I have no idea why.
