### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Zahrun** [lakinduakash/linux-wifi-hotspot#308]
Hi there,

Would it be possible to create a new release?
I would like to have https://github.com/lakinduakash/linux-wifi-hotspot/pull/237 included in a release.

Thanks

**Comment by lakinduakash** [comment]
Sure, I'll do that. I lost the signing key, I'm requesting new key and I'll
publish new version. Thanks

**Comment by Zahrun** [comment]
Will the github release of [wihotspot-v4.5.0](https://github.com/lakinduakash/linux-wifi-hotspot/releases/tag/v4.5.0) get a .deb file?

**Comment by lakinduakash** [comment]
I'm working on that. Currently, I don't have a Debian or Ubuntu machine to do that. It's hard to test on a virtual machine. Sorry for the wait. Until that, you can build it yourself

**Comment by lakinduakash** [comment]
I recovered the key and the new version has been published

**Comment by Zahrun** [comment]
Thank you <3
