### ISSUE TITLE
App not opening 

### ISSUE THREAD

**Issue by kabrownie** [lakinduakash/linux-wifi-hotspot#309]
**Describe the bug**
when click on the wi hotspot icon it is not running.
It was working well until last week. I have tried reinstalling it but still it is not running.
when I try running using terminal it displays Segmentation fault (core dumped)

![Screenshot from 2023-04-25 21-02-36](https://user-images.githubusercontent.com/75438336/234365900-102143ba-e81d-4009-acb8-24f8ae008947.png)

**Desktop :**
 OS: [Ubuntu]
Version [ 20.04]

**Comment by lakinduakash** [comment]
Can you try building it yourself and run it?

**Comment by kabrownie** [comment]
I  Removed repository cache and it worked.

sudo apt-get clean all
