### ISSUE TITLE
Hotspot is 5Ghz even tho it's set to 2.4, clicking 2.4 and running again runs it in 2.4 normally

### ISSUE THREAD

**Issue by ZeroKun265** [lakinduakash/linux-wifi-hotspot#312]
**Describe the bug**
While trying to get it set up i noticed that, if you start the app it shows the latest settings used (as it should) but if the GUI showed 2.4Ghz beeing selected, pressing create hotspot would create a 5Ghz hotspot (wwhich wasn't visible to a friend's laptop but it was to my phone, and it showed 5G icon near it)
Stopping the hotspot, clicking 2.4Ghz (even if it's already clicked) (or switching from another option back to 2.4) and starting again fixes it

**To Reproduce**
1. Open the app and select 2.4Ghz (maybe you need to start the hotspot)
2. Close the app and reopen it
3. See that in the advanced tab it still says 2.4Ghz
4. Start the hotspot
5. See that it's 5Ghz
6. Apply "fix" like above and try again, now it's 2.4Ghz

**Expected behavior**
It should directly start on 2.4Ghz OR AT LEAST show 5Ghz, showing the status of the hotspot that would be created

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Kernel version: 6.2.13-arch1-1 (64-bit)
 - Kde Plasma version: 5.27.4
 - Kde framweorks version: 5.105.0
 - Qt Version: 5.15.9
 - network manager: NetworkManager

**Comment by ZeroKun265** [comment]
Oh i forgot to say i use the iwd backend, idk if it's necessary, i think it's just a ui issue but could not so, yeah

**Comment by lakinduakash** [comment]
Can you check latest relese fixed this?
