### ISSUE TITLE
Doesn't see my adapter as Wi-fi interface

### ISSUE THREAD

**Issue by Kopetan4egX** [lakinduakash/linux-wifi-hotspot#319]
I have a tp-link tl-wn722n wi-fi adapter. According to "iw list" command it supports creating an AP. But Wifi-hotspot doesn't recognize adapter as wi-fi interface, only as internet interface, so i can't create access point using it.

![image](https://github.com/lakinduakash/linux-wifi-hotspot/assets/18350912/c6c07e61-28de-4c23-916b-51f114fc25a5)

 - OS: Debian Testing 
 - uname -a "Linux  6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux"
- for adapter i'm using driver from https://github.com/ivanovborislav/rtl8188eu

**Comment by lakinduakash** [comment]
Can you list the output of `iw dev`

**Comment by Kopetan4egX** [comment]
> Can you list the output of `iw dev`
`phy#0
	Interface wlx14ebb6191a69
		ifindex 3
		wdev 0x1
		addr 
		type managed
		txpower -100.00 dBm
`

**Comment by amit112amit** [comment]
I have a similar issue on Debian Testing.  When I launch the GUI as a regular user, the Wi-Fi adapter dropdown is empty but when I launch it as the root user using the terminal, my WiFi adapter is listed in the dropdown. Can you try launching the GUI with sudo?

**Comment by Kopetan4egX** [comment]
> I have a similar issue on Debian Testing. When I launch the GUI as a regular user, the Wi-Fi adapter dropdown is empty but when I launch it as the root user using the terminal, my WiFi adapter is listed in the dropdown. Can you try launching the GUI with sudo?

Thanks, it works with sudo. I can't connect to the AP with my phone, but that's another question.

**Comment by amit112amit** [comment]
Related to this issue: When I run `wihotspot` from the terminal without `sudo`, I see a message saying `iw not found`. So I created a symlink using `sudo ln -s /usr/sbin/iw /usr/bin/iw`. After this, I am able to run `wihotspot` without `sudo` and the hotspot is getting created.

**Comment by Kopetan4egX** [comment]
> Related to this issue on Debian: When I run `wihotspot` from the terminal without `sudo`, I see a message saying `iw not found`. So I created a symlink using `sudo ln -s /usr/sbin/iw /usr/bin/iw`. After this, I am able to run `wihotspot` without `sudo` and the hotspot is getting created.


Thank you! It works. 
It's strange still, because when i earlier ran `wihotspot` from the terminal without `sudo` it still asked **twice** for superuser password before actually opening the application, and entering password didn't help.
Also now my phone connects without any problem, it couldn't do so for some reasons when i was running app as superuser for some reasons, as I mentioned before.
