### ISSUE TITLE
Ubuntu unable to connect to internet after usage

### ISSUE THREAD

**Issue by Lblenner** [lakinduakash/linux-wifi-hotspot#328]
**Describe the bug**

After running linux-wifi-hotspot, the wifi settings shows "No Wi-fi Adapter found" even after restart. I could not find an easy way to make the wifi work again.

**To Reproduce**

My environment is not heavely customized.
I don't know what part of the system is at fault

**Expected behavior**

Ubuntu should be able to connect back to internet after using the app (or at least after restart)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04 LTS

**Additional context**

I'm not asking for a fix but I want to inform that this behaviour exists

It seems to be mentioned here also :
https://github.com/lakinduakash/linux-wifi-hotspot/issues/287

**Comment by Lblenner** [comment]
The problem was fixed by manually editing `/etc/NetworkManager/NetworkManager.conf` and removing

**Comment by lvsz** [comment]
> `make_ap --fix-unmanaged` fixes the problem.

The command is `create_ap --fix-unmanaged` but yes, it did fix it for me, thank you.
