### ISSUE TITLE
Problem in sudo make install

### ISSUE THREAD

**Issue by Sh4d0wx0x5F** [lakinduakash/linux-wifi-hotspot#331]
[sudo] password for kali: 
Installing...
cd src && make install
make[1]: Entering directory '/home/kali/linux-wifi-hotspot/src'
make[1]: *** No rule to make target '../build/wihotspot-gui', needed by 'install'.  Stop.
make[1]: Leaving directory '/home/kali/linux-wifi-hotspot/src'
make: *** [Makefile:9: install] Error 2

when i run the sudo make install command in cd /home/kali/linux-wifi-hotspot/ , it's giving error 

please help

**Comment by karanverma69** [comment]
same error please help

**Comment by Arafat05nov** [comment]
Did you tried deleting it then reinstalling it again

**Comment by Arafat05nov** [comment]
I installed some kali builds and it solved my issue
