### ISSUE TITLE
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time

### ISSUE THREAD

**Issue by genshishio48** [lakinduakash/linux-wifi-hotspot#35]
Please help me
nizam@Nizam:~$ sudo wihotspot
[sudo] password for nizam:         
create_ap wlp2s0 wlp2s0 COMXIPAD jenengmu --mkconfig /home/nizam/.wh.config --mac aa:aa:aa:aa:aa:aa 
Config options written to '/home/nizam/.wh.config'
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time
Command not found or exited with error status

**Comment by lakinduakash** [comment]
Did you try it with 2.4Ghz band? Add '--freq-band 2.4' to options and remove config file or change frequency in gui.

**Comment by genshishio48** [comment]
> Did you try it with 2.4Ghz band? Add '--freq-band 2.4' to options and remove config file or change frequency in gui.

still same

**Comment by lakinduakash** [comment]
Can you post the output of  `iw list` under _**Supported interface modes:**_  with

**Comment by genshishio48** [comment]
> Can you post the output of `iw list` under _**Supported interface modes:**_ with
here	
Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * mesh point
		 * P2P-client
		 * P2P-GO

**Comment by lakinduakash** [comment]
Do `iw dev wlp2s0 info` give you an output with `type managed`?
I think the issue is in function at [create_ap#L281](https://github.com/lakinduakash/linux-wifi-hotspot/blob/5209290e59d0d44fc10f4f809a4f68738dd791b8/src/scripts/create_ap#L281) returns 1. Maybe it use `iwconfig` instead of `iw`. can you manually set $USE_IWCONFIG=0 before evaluating the function at  [create_ap#L281](https://github.com/lakinduakash/linux-wifi-hotspot/blob/5209290e59d0d44fc10f4f809a4f68738dd791b8/src/scripts/create_ap#L281) and check whether working ?

**Comment by genshishio48** [comment]
> Do `iw dev wlp2s0 info` give you an output with `type managed`?
yes nizam@Nizam:~$ iw dev wlp2s0 info
Interface wlp2s0
	ifindex 3
	wdev 0x1
	addr f0:03:8c:65:47:ef
	ssid @wifi.id
	type managed
	wiphy 0
	channel 1 (2412 MHz), width: 20 MHz, center1: 2412 MHz
	txpower 20.00 dBm

> I think the issue is in function at [create_ap#L281](https://github.com/lakinduakash/linux-wifi-hotspot/blob/5209290e59d0d44fc10f4f809a4f68738dd791b8/src/scripts/create_ap#L281) returns 1. Maybe it use `iwconfig` instead of `iw`. can you manually set $USE_IWCONFIG=0 before evaluating the function at [create_ap#L281](https://github.com/lakinduakash/linux-wifi-hotspot/blob/5209290e59d0d44fc10f4f809a4f68738dd791b8/src/scripts/create_ap#L281) and check whether working ?
i will try it

**Comment by naveenjohnsonv** [comment]
Facing same issue. Similar iw list and iw dev wlp3s0 gives type managed.
Tried, 
sudo create_ap --config /home/nj/wh.config with the option USE_IWCONFIG=0

Returns:
WARN: Unrecognized configuration entry USE_IWCONFIG
ERROR: Your adapter can not be a station (i.e. be connected) and an AP at the same time

Any fix?

**Comment by lakinduakash** [comment]
@naveenjohnsonv can you manually set $USE_IWCONFIG=0 before evaluating the function at [create_ap#L281](https://github.com/lakinduakash/linux-wifi-hotspot/blob/5209290e59d0d44fc10f4f809a4f68738dd791b8/src/scripts/create_ap#L281) (not in the config file, change it in the source code) and check whether working?

**Comment by naveenjohnsonv** [comment]
> @naveenjohnsonv can you manually set $USE_IWCONFIG=0 before evaluating the function at [create_ap#L281](https://github.com/lakinduakash/linux-wifi-hotspot/blob/5209290e59d0d44fc10f4f809a4f68738dd791b8/src/scripts/create_ap#L281) (not in the config file, change it in the source code) and check whether working?


Like this?

![Screenshot from 2020-09-07 20-48-20](https://user-images.githubusercontent.com/14140949/92401583-94d43d80-f14b-11ea-907b-d213b0db909c.png)

**Comment by lakinduakash** [comment]
Yes. Did you get any result?

**Comment by naveenjohnsonv** [comment]
I'm afraid not. Same error.

**Comment by Smankusors** [comment]
do you mean `USE_IWCONFIG=0`? If I'm using `$USE_IWCONFIG=0`, I got `/usr/bin/create_ap: line 228: =0: command not found`
