### ISSUE TITLE
How to persist settings and create hotspots by opening them

### ISSUE THREAD

**Issue by muyiacc** [lakinduakash/linux-wifi-hotspot#354]
**Is your feature request related to a problem? Please describe.**
How to persist settings and create hotspots by opening them

**Describe the solution you'd like**
Opening the software allows you to select existing configurations, but entering them every time is too cumbersome

**Describe alternatives you've considered**
none

**Additional context**
none.

**Comment by lakinduakash** [comment]
Which fields are not filling from previous steps? it saves dome configs and loads by defualt

**Comment by lakinduakash** [comment]
Closes as inactive
