### ISSUE TITLE
Wifi Interface blocked from choosing interface

### ISSUE THREAD

**Issue by NoamReuveni** [lakinduakash/linux-wifi-hotspot#364]
**Describe the bug**
I follow the guidlines and tried to create a hotspot.
Once running as sudo the app I couldn't choose a wifi interface (see screenshot to see difference of color between Wifi Interface and Internet interface).
I then thought there is just one wifi interface to choose from and it does by default but when trying to create hotspot I got the following text:

Please select Wifi and Internet interfaces
pkexec --user root create_ap wlan0 eth0 'MyAccessPoint' '12345678' --mkconfig /etc/create_ap.conf --freq-band 2.4 --mac  -g XXX.XXX.XX.X 
Config options written to '/etc/create_ap.conf'
ERROR: 'wlan0' is not a WiFi interface
Command not found or exited with error status

**To Reproduce**
1. Follow installation guide (including compiling and building)
2. Run `sudo wihotspot` from terminal
3. Chosse Internet interface
4. Click Create Hotspot and look at terminal where it is run

**Expected behavior**
I wold expect to be able to choose the wifi interface and be able to create a hotspot

**Screenshots**
![image](https://github.com/lakinduakash/linux-wifi-hotspot/assets/76475420/4e9f734a-2283-47b7-951a-e9a931c235b8)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**
I tried running the app not as sudo from terminal and from the gui app that was created and all of the options led to the same bug

**Comment by Tiebe** [comment]
Make sure you have `iw` installed. That was the problem for me.

**Comment by lakinduakash** [comment]
@NoamReuveni did you check whether all the dependencies are installed as in the README? Please check `iw` also.
