### ISSUE TITLE
I can not click on Wifi interface 

### ISSUE THREAD

**Issue by Mohan-Sundara** [lakinduakash/linux-wifi-hotspot#379]
**Describe the bug**
I am using Boss linux os.
In the GUI, I can't able to click on wifi-interface, so I can't choose wifi interface. So, I can't able to start the hotspot. 
Error in terminal as follows
pkexec --user root create_ap wlan0 eth0 'MyAccessPoint' '12345678' --mkconfig /etc/create_ap.conf --mac -g -g 192.168.12.1 
Config options written to '/etc/create_ap.conf'
ERROR: 'wlan0' is not a WiFi interface
Command not found or exited with error status

![Screenshot from 2024-02-17 18-19-55](https://github.com/lakinduakash/linux-wifi-hotspot/assets/160324889/26aac411-0ad2-4f04-8fce-dd0d287d13a2)

Kindly help to solve the issue
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 18.04]

**Additional context**

**Comment by lakinduakash** [comment]
Check `iw` command is available.

**Comment by Mohan-Sundara** [comment]
iw: not found
I have attached terminal screenshot for your reference.
What can I do now?
Kindly let me know.
![Screenshot from 2024-02-19 11-11-31](https://github.com/lakinduakash/linux-wifi-hotspot/assets/160324889/e3afee92-709e-4572-91a1-a3260d3362c5)

**Comment by lakinduakash** [comment]
Please install `iw` and dependencies. Please chek https://github.com/lakinduakash/linux-wifi-hotspot?tab=readme-ov-file#dependencies

**Comment by Mohan-Sundara** [comment]
Thank you for your quick response.
I have installed iw but still in terminal it is showing iw: not found.
I have attached terminal screenshot for your reference.

Actually I don't know much about computers and softwares and new to linux os. 
I am learning things one by one by browsing in internet.
Kindly let me know what to do now.
![Screenshot from 2024-02-19 11-47-21](https://github.com/lakinduakash/linux-wifi-hotspot/assets/160324889/fd0e143e-0a40-4853-883c-cc4b118d521b)

**Comment by lakinduakash** [comment]
Can you check `which iw` and find it in your `$PATH` variable?
It seems like even though `iw` is installed it is not in your `$PATH` env variable

**Comment by Mohan-Sundara** [comment]
I have fixed that problem 
Still it shows error  (see image)
I have used wifi and hotspot at the same in this same device with windows os.
What can I do now?

![Screenshot from 2024-02-21 16-02-51](https://github.com/lakinduakash/linux-wifi-hotspot/assets/160324889/2ab18914-d6a6-4f54-87e5-7e204b41745d)

**Comment by purna42** [comment]
Hi @Mohan-Sundara : How you fixed the not able to click error? I have Ubuntu 20 OS and I am facing this same issue. Please let me know

**Comment by Mohan-Sundara** [comment]
You may try installing all the dependencies.
Check everything and read the hotspot page in git hub page properly.
Run again.



With regards,
Mohan S.
