### ISSUE TITLE
Secondary WiFi interface.

### ISSUE THREAD

**Issue by 01-pratham** [lakinduakash/linux-wifi-hotspot#38]
**Feature: Adding a secondary WiFi interface (external WiFi antenna/USB adapter) for hotspot.**

The USB adapter shows up as `wlan1` when typing `ip a` in terminal. It also shows up when selecting _Internet Interface_ in wihotspot, but doesn't show up in _WiFi interface._

The USB adapter works as an AP when I follow the [Official Raspberry Pi](https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md) guide.

<img width="1092" alt="Screenshot 2019-12-25 at 10 10 37" src="https://user-images.githubusercontent.com/44400303/71432349-058f1300-26ff-11ea-9935-e84e2f8906c0.png">wlan1 doesn't show up in WiFi interface.

<img width="1092" alt="Screenshot 2019-12-25 at 10 11 04" src="https://user-images.githubusercontent.com/44400303/71432350-0627a980-26ff-11ea-9d5d-090d8fe13f96.png">wlan1 shows up in Internet Interface.

**Comment by lakinduakash** [comment]
Hey,
Thank you for pointing out. :)
Can you show the output of `iw dev`
