### ISSUE TITLE
No available wifi interface

### ISSUE THREAD

**Issue by nondrinkingdio** [lakinduakash/linux-wifi-hotspot#383]
There're no available wifi interface.
![image](https://github.com/lakinduakash/linux-wifi-hotspot/assets/30740027/8e9f7115-14ea-4255-a41c-36e70b341b1c)

 I've seen several issues about this, I've installed all the dependencies and I think it's the issue of  wireless adapter since when I enter iw dev, it returned nothing
![image](https://github.com/lakinduakash/linux-wifi-hotspot/assets/30740027/cfb8061f-a4d0-4318-9f8c-f02e18d43dcd)
I ran ubuntu 22.04 on a vitural machine(VMware Workstation). I wondered if I can use my laptop wireless adpater(Killer Wireless-n/a/ac 1535 Wireless Network Adapter) as the virtual machine wireless adapter. If so, how? If not, are there other solutions.

**Comment by lakinduakash** [comment]
It is not possible to access host's wireless adapter via guest OS (virtual machine). The only way to use a wireless adapter is through USB wireless adapter

**Comment by purna42** [comment]
@lakinduakash : I am not trying from the host, but using wifi adapter and facing this issue, how do I resolve, OS is Ubuntu 20
