### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by juanito665** [lakinduakash/linux-wifi-hotspot#386]
**Describe the bug**
when i tried to install wifi hotspot, the permissions to install it was denied for some reason

**To Reproduce**
1. open debian
2. copy and paste git clone https://github.com/lakinduakash/linux-wifi-hotspot
cd linux-wifi-hotspot

#build binaries
make

#install
sudo make install and press enter
3. it appears that all files and programs have permission denied

**Expected behavior**
i expected that wifi hotspot would be installed

**Screenshots**
![Captura de pantalla 2024-03-25 214957](https://github.com/lakinduakash/linux-wifi-hotspot/assets/164965691/1d1a1d24-86f0-4e96-8f7b-4dad2f1ad586)

**Desktop (please complete the following information):**
 - OS: debian
 - Version: 12

**Comment by Marquezv** [comment]
probably you didn't install all the necessary libraries (I had the same problem, I use the same version of Debian), use this command, described in the project's README: sudo apt install -y libgtk-3-dev build-essential gcc g++ pkg-config make hostapd libqrencode-dev libpng-dev

**Comment by juanito665** [comment]
![Captura de pantalla 2024-03-29 203546](https://github.com/lakinduakash/linux-wifi-hotspot/assets/164965691/0d329731-70c0-4771-9319-1eadf7123f4b)

It didn´t work :c

**Comment by lakinduakash** [comment]
You don't have write permission in current directory. Go to your users home
directory and git clone again. You are inside /root which is not writable
unless you are root user.
This is not a application related issue.
