### ISSUE TITLE
E: Unable to locate package linux-wifi-hotspot

### ISSUE THREAD

**Issue by Semro** [lakinduakash/linux-wifi-hotspot#396]
I was trying to install app on Ubuntu with README instruction: https://github.com/lakinduakash/linux-wifi-hotspot?tab=readme-ov-file#installation
But on  `sudo apt install linux-wifi-hotspot` there is an error:
E: Unable to locate package linux-wifi-hotspot

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Version: 23.10

**Comment by VoidDave** [comment]
I know its late responce. But i managed to succesfuly run this program on fresh install of kubuntu. I needed all dependencies and build it from source myself. Hope its gona help you : ) (all instruction are located bellow files in readne)

**Comment by Semro** [comment]
Yes, building from source worked for me, but still it would be great to have an option to install from package manager and receive updates.

**Comment by DanielRuf** [comment]
Did you add the PPA like described in the readme?

**Comment by Semro** [comment]
Sorry, it was on my side.  My PC couldn't connect to `ppa.launchpadcontent.net` when I was adding apt repository.
