### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by arismelachroinos** [lakinduakash/linux-wifi-hotspot#40]
**Describe the bug**
I have 2 wireless adapters, wlan0 is connected to an AP. I want wlan1 to make a hotspot, forwarding the internet connection of wlan0. The hotspot AP is being created fine, and is visible from my phone, however when I connect to it, there is no internet connection. 

**To Reproduce**
1. Have 2 wireless adapters
2. Connect wlan0 to an AP
3. type `wihotspot`
4. Set an SSID and Password.
5. Set Wifi Interface to "wlan1"
6. Set Internet Interface to "wlan0"
7. Click "Create hotspot"
8. No error appears. If I connect my mobile phone to the hotspot AP, I get "Connected, no internet". I tried it on a Windows laptop as well.
9. I also tried it with only one interface, and without a password, and with 2.4Ghz option.

**Expected behavior**
My mobile phone that is connected to the hotspot AP should be able to connect to the internet.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2020.2

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 XL
 - OS: Android 10

**Comment by lakinduakash** [comment]
Thank you for reporting. I have not tested for such a situation. It creates a bridge connection between interfaces anyway. I could not figure out why is that immediately. If you can, try to find the cause of that problem. :)

**Comment by arismelachroinos** [comment]
It is fixed now for some reason. Thank you.

**Comment by denomparkour** [comment]
> It is fixed now for some reason. Thank you.

How? I'm facing same issue

**Comment by Fox595676** [comment]
> > It is fixed now for some reason. Thank you.
> 
> How? I'm facing same issue

Same! Can I have some help please?
