### ISSUE TITLE
this completely bricked my wifi card

### ISSUE THREAD

**Issue by LukeDevsEAlt** [lakinduakash/linux-wifi-hotspot#411]
**Describe the bug**
I used this program on a usb stick, and turned off my computer and booted back into windows
and the card dosent appear in linux, neither windows (in windows device manager it says This device cant start, error code 10)
**To Reproduce**
1. use the program
2. turn off linux

**Expected behavior**
to not completely brick my wifi card

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 23.10.1

**Additional context**
when i run `sudo lshw -c network` it now says *-network UNCLAIMED

**Comment by LukeDevsEAlt** [comment]
forgot to mention my wifi card is a RZ608 (rebranded MediaTek MT7921K)

**Comment by Holopsic0n** [comment]
really? I have the same RZ608 on Asrock B650 PG Riptide Gaming.

**Comment by LukeDevsEAlt** [comment]
anyways i just fixed it by reinstalling drivers in windows
