### ISSUE TITLE
PPA does not have Release file for "noble"

### ISSUE THREAD

**Issue by MikeBishop** [lakinduakash/linux-wifi-hotspot#416]
**Describe the bug**
Latest Ubuntu doesn't find the PPA

**To Reproduce**
1. Install Ubuntu 24.04 (noble)
2. Run `sudo add-apt-repository ppa:lakinduakash/lwh && sudo apt update`
3. See error

```
E: The repository 'https://ppa.launchpadcontent.net/lakinduakash/lwh/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Expected behavior**
PPA is used to fetch apt packages

**Comment by jmara09** [comment]
Did you ever find a fix for this problem?

**Comment by lakinduakash** [comment]
Sorry for the delay. I just synced those packages for several Ubuntu
versions and hopefully they will be available in few hours
