### ISSUE TITLE
Suggest an logo

### ISSUE THREAD

**Issue by lakinduakash** [lakinduakash/linux-wifi-hotspot#42]
Anyone welcome to suggest a logo for this project.
The logo should be unique and simple. Add a **SVG** file to `docs/logo` folder.
PS: Don't suggest logos from the internet

**Comment by freddii** [comment]
Old logo edited as zip and as svg.

So the old logo can be used as svg until a the decision about a new logo is done.

[hotspot-logo.zip](https://github.com/lakinduakash/linux-wifi-hotspot/files/5795134/hotspot-logo.zip)
![hotspot_logo](https://user-images.githubusercontent.com/7213207/104169510-f9f0b600-53ff-11eb-9551-b1406b498361.png)

**Comment by lakinduakash** [comment]
Hi, thank you. I will check this.

**Comment by freddii** [comment]
I added some white to the back of the black. 
So the icon is also good visible in dark mode desktops.

![hotspot](https://user-images.githubusercontent.com/7213207/105113719-bfed7700-5ac5-11eb-874e-90df6263a063.png)

**Comment by lakinduakash** [comment]
New icon added to the master branch
