### ISSUE TITLE
Issues running the GUI with root

### ISSUE THREAD

**Issue by yochananmarqos** [lakinduakash/linux-wifi-hotspot#44]
**Describe the bug**
The desktop file attempts to use `pkexec` and `sudo` at the same time and fails.

**To Reproduce**
Use the desktop shortcut / command

**Expected behavior**
...

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: GNOME 3.36.2

**Additional context**

```
$ pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sudo /usr/bin/wihotspot
create_ap wlan0 wlan0 test  --mkconfig /root/.wh.config -c 1 
Config options written to '/root/.wh.config'
```

```
$ wihotspot 
Couldn't open config file for reading.
You must run it as root.
Command not found or exited with error status
create_ap wlan0 wlan0 test  --mkconfig /home/yochanan/.wh.config 
```

This is the issue with running a GUI as root. What are you doing using `pkexec` and `sudo` in the same command? 

The config file was not written at all. Config files should be something like, `/etc/wihotspot/wh.conf` or `~/.config/wihotspot/wh.conf`. 

It also cannot create a hotspot, but I'm not going to troubleshoot further as I'm stopping right here and won't attempt to use this program until the original issue is fixed.

**Comment by yochananmarqos** [comment]
Nevermind, I give up. This also conflicts with the `create_ap` package as you're attempting to include it?

```
error: failed to commit transaction (conflicting files)
linux-wifi-hotspot-git: /etc/create_ap.conf exists in filesystem (owned by create_ap)
linux-wifi-hotspot-git: /usr/bin/create_ap exists in filesystem (owned by create_ap)
linux-wifi-hotspot-git: /usr/lib/systemd/system/create_ap.service exists in filesystem (owned by create_ap)
linux-wifi-hotspot-git: /usr/share/bash-completion/completions/create_ap exists in filesystem (owned by create_ap)
linux-wifi-hotspot-git: /usr/share/doc/create_ap/README.md exists in filesystem (owned by create_ap)
```

**Comment by lakinduakash** [comment]
Hi,
The issue is confirmed. I will look forward to it.

**Comment by lakinduakash** [comment]
I think the issue is with gnome 3.36.1 and up. It worked previously.

**Comment by lakinduakash** [comment]
> Nevermind, I give up. This also conflicts with the `create_ap` package as you're attempting to include it?
> 
> ```
> error: failed to commit transaction (conflicting files)
> linux-wifi-hotspot-git: /etc/create_ap.conf exists in filesystem (owned by create_ap)
> linux-wifi-hotspot-git: /usr/bin/create_ap exists in filesystem (owned by create_ap)
> linux-wifi-hotspot-git: /usr/lib/systemd/system/create_ap.service exists in filesystem (owned by create_ap)
> linux-wifi-hotspot-git: /usr/share/bash-completion/completions/create_ap exists in filesystem (owned by create_ap)
> linux-wifi-hotspot-git: /usr/share/doc/create_ap/README.md exists in filesystem (owned by create_ap)
> ```

Yes. This is gui wrapper for it
