### ISSUE TITLE
Port Forwarding(?)

### ISSUE THREAD

**Issue by Akrista** [lakinduakash/linux-wifi-hotspot#46]
Hi! sorry, i'm new here and using linux, there's a way to open ports of the wifi AP? cause for some programs seems to be port block when i use the create_ap only trough WPA, but when using bridging i don't have this issue

**Comment by lakinduakash** [comment]
Sorry for the late reply. I don't understand the term port. This only interacts with the network layer and below layers. So this program does not relate to any port which is in the transport layer.
