### ISSUE TITLE
Linking error due to multiple definitions of running_info

### ISSUE THREAD

**Issue by ragouel** [lakinduakash/linux-wifi-hotspot#47]
<pre><code>/usr/bin/ld: CMakeFiles/wihotspot.dir/ui/ui.c.o:(.bss+0x10): multiple definition of `running_info'; CMakeFiles/wihotspot.dir/ui/h_prop.c.o:(.bss+0x420): first defined here
collect2: error: ld returned 1 exit status</code></pre>
[install.log](https://github.com/lakinduakash/linux-wifi-hotspot/files/4681884/install.log)

**To Reproduce**
1. Clone repo
2. cd into linux-wifi-hotspot
3. run make && sudo make install

**Desktop:**
 - OS: Arch Linux 4.20
 - gcc version 10.1.0
- ld version 2.34
- cmake 3.17.2

**Comment by lakinduakash** [comment]
I don't get such an error. What is your cmake version?

**Comment by ragouel** [comment]
3.17.2
