### ISSUE TITLE
Connected Devices

### ISSUE THREAD

**Issue by dotx** [lakinduakash/linux-wifi-hotspot#49]
It works great on Ubuntu 20.04 so far, many thanks !!
this is more of a feature request. Can we see who is connected to the hotspot. Also, is it possible to have this as an extension, that can be enabled or disabled from the top bar from the desktop.

Again, many thanks !

**Comment by lakinduakash** [comment]
> It works great on Ubuntu 20.04 so far, many thanks !!

Nice to hear!

> this is more of a feature request. Can we see who is connected to the hotspot. Also, is it possible to have this as an extension, that can be enabled or disabled from the top bar from the desktop.
> 

Yes, that is possible. Currently, I don't have time to implement that soon. If you are interested you can contribute.
