### ISSUE TITLE
How to see which devices are connected through the hotspot?

### ISSUE THREAD

**Issue by Puspam9876** [lakinduakash/linux-wifi-hotspot#50]
It would be great if this important feature can be integrated into the application and connected devices can be shown on the tray on status bar, and to get an alert when a new device gets connected or disconnected. It is always a good idea to check for connected devices to avoid security flaws.

**Comment by lakinduakash** [comment]
Duplicate of #49

**Comment by lakinduakash** [comment]
If you are interested you can work on this.. :)
