### ISSUE TITLE
Restore a normal situation when stopping hotspot

### ISSUE THREAD

**Issue by Patrick-81** [lakinduakash/linux-wifi-hotspot#51]
When stopping the hotspot all connection type are lost to the PC or RPi. I need to connect a kbd and a display to take control on the PC or board.
It would be nice to only cut the bridge between internet connection and hotspot connection but keep the access to the PC or RPi board via wifi or RJ45 wire.
Thanks for your answer

**Comment by lakinduakash** [comment]
This only stops hotspot only when you press stop. What is the OS you tested it?
