### ISSUE TITLE
Cmake is installed but linux-wifi-hotspot is not able to detect it.

### ISSUE THREAD

**Issue by tarunsac** [lakinduakash/linux-wifi-hotspot#52]
**Describe the bug**
Cmake is installed but linux-wifi-hotspot is not able to detect it.
**To Reproduce**
1. When trying to install linux-wifi-hotspot it fails with the error message "cmake: not found". See the terminal output below...
(base) tarun@tarun-vostro-3480:~/linux-wifi-hotspot$ sudo make install
[sudo] password for tarun: 
Installing
cd build && cmake -DCMAKE_INSTALL_PREFIX= -G "CodeBlocks - Unix Makefiles" ../src
/bin/sh: 1: cmake: not found
Makefile:8: recipe for target 'install' failed
make: *** [install] Error 127
2. Verified that cmake is installed. See the terminal output below...
(base) tarun@tarun-vostro-3480:~/linux-wifi-hotspot$ cmake --version
cmake version 3.13.4

3. $PATH is also updated accordingly. See the terminal output below...
(base) tarun@tarun-vostro-3480:~/linux-wifi-hotspot$ echo $PATH
/home/tarun/.local/bin:/home/tarun/anaconda3/bin:/home/tarun/anaconda3/condabin:/home/tarun/.local/bin:/opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/tarun/cmake-3.13.4-Linux-x86_64/bin

4. Also, verified that I can check cmake version from any other directory as well, like root
(base) tarun@tarun-vostro-3480:~/linux-wifi-hotspot$ cd /
(base) tarun@tarun-vostro-3480:/$ pwd
/
(base) tarun@tarun-vostro-3480:/$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Expected behavior**
linux-wifi-hotspot should be able to detect cmake properly

**Desktop (please complete the following information):**
 - OS & Version 

(base) tarun@tarun-vostro-3480:/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Additional context**
I am also not able to launch the program using wihotspot
(base) tarun@tarun-vostro-3480:~/linux-wifi-hotspot$ wihotspot
wihotspot: command not found

**Comment by lakinduakash** [comment]
You have to first run just `make` command inside the project folder. Then execute the `sudo make install`. Also I think your path is only valid for the current user. So don't execute `make` as the root user. Refer the README. Follow the bellow order.

```
git clone https://github.com/lakinduakash/linux-wifi-hotspot
cd linux-wifi-hotspot

#build binaries
make

#install
sudo make install
```
