### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by sanjeebSubedi** [lakinduakash/linux-wifi-hotspot#54]
When I try to start the hotspot, it always says not running 
![image](https://user-images.githubusercontent.com/51266822/89702696-9f8c8e80-d963-11ea-8aa1-91babaeac80d.png)

**Comment by lakinduakash** [comment]
Can you try to start from command line by typing `wihotspot` and print the output?

**Comment by sanjeebSubedi** [comment]
says your adapter does not support AP mode. But I can create hostpot on windows without any problem.

**Comment by lakinduakash** [comment]
Can share the vendor of your wifi adapter? (Ex: Intel, Qualcomm)

**Comment by sanjeebSubedi** [comment]
Its broadcom

**Comment by sanjeebSubedi** [comment]
I think there is no linux driver that supports AP mode for bcm43142 chipset.
