### ISSUE TITLE
Add instructions and examples on how to run and build without the UI 

### ISSUE THREAD

**Issue by ofirule** [lakinduakash/linux-wifi-hotspot#56]
Add instructions and examples on how to run and build without the UI

**Comment by lakinduakash** [comment]
Hi, this program is not intended to run on containers such as dockers. Because this needs real hardware (Wifi adapters) )to actually utilize this. What do you intend to run this in a docker?

**Comment by ofirule** [comment]
This is the wrong thread for talking about containers

**Comment by lakinduakash** [comment]
Maybe. I don't have a clear idea of it. The GUI is actually a wrapper around `create_ap` command line. So I think that part can be integrated into a docker. If you are interested you can work on this.

**Comment by lakinduakash** [comment]
I'm sorry about this. I got mixed up with your #57 issue. :D

**Comment by lakinduakash** [comment]
You can refer https://github.com/lakinduakash/linux-wifi-hotspot/edit/master/src/scripts/README.md
