### ISSUE TITLE
Investigate installation using docker image

### ISSUE THREAD

**Issue by ofirule** [lakinduakash/linux-wifi-hotspot#57]
Investigate installation using a docker image

**Comment by ofirule** [comment]
I guess it's possible to map everything (No UI) inside a container when mapping devices and network interfaces. Maybe not all features will work, but it requires some investigation. This could be a nice and easy deploy for an IOT device (e.g raspberry pi)

**Comment by lakinduakash** [comment]
That is great. If you are interested you can investigate and add your contributions. This is actually GUI wrapper around `create_ap` command. So you can refer it.
