### ISSUE TITLE
Not running on both frequency band

### ISSUE THREAD

**Issue by stevenfang1997** [lakinduakash/linux-wifi-hotspot#59]
I'm on Manjaro KDE.

Here is my settings:
![image](https://user-images.githubusercontent.com/37974764/94237583-6f6c6f80-ff52-11ea-941a-d6beccb414e7.png)

The app shows "not running" regardless which frequency band I tries to connect.

Here is the command console output If I connect to 5Ghz frequency:
`pkexec --user root create_ap wlp0s20f3 wlp0s20f3 Hotspot  --mkconfig /etc/wh.config --freq-band 5` 
`Config options written to '/etc/wh.config'`

`ERROR: Your adapter can not transmit to channel 36, frequency band 5GHz.`

`Command not found or exited with error status`

Here is the command console output If I connect to 2.4Ghz frequency:
`pkexec --user root create_ap wlp0s20f3 wlp0s20f3 Hotspot  --mkconfig /etc/wh.config --freq-band 2.4`
`Config options written to '/etc/wh.config'`

`dnsmasq: cannot read /tmp/create_ap.wlp0s20f3.conf.rt3jez23/dnsmasq.conf: Permission denied`
`Command not found or exited with error status`

Is there any workaround to solve this? Thank you!

**Comment by lakinduakash** [comment]
Can you try to execute this with your 2.4GHz config `sudo create_ap --config /etc/wh.config` and check the status? 
Also, try to force delete the `/tmp/create_ap.*` folder and then restart the computer. Then try to execute above again or from GUI.
And there are some issues with Linux WiFi drivers when creating AP with 5GHz bands.

**Comment by stevenfang1997** [comment]
Thanks for your reply. After inputting `sudo create_ap --config /etc/wh.config` and execute with 2.4GHz config, I have this output:

`pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'Hotspot' '' --mkconfig /etc/wh.config --freq-band 2.4`
`Config options written to '/etc/wh.config'`

`dnsmasq: cannot read /tmp/create_ap.wlp0s20f3.conf.4GN9TwjH/dnsmasq.conf: Permission denied`
`Command not found or exited with error status`

I couldn't find any `/tmp/create_ap.*` folder. I did find a `create_ap.all.lock` file in my  `/tmp/` folder. Do you think this it's relevant? Should I delete this and restart the computer?

I'm using a WPA/WPA2 Enterprise wifi. Do you think this might cause the "not running" problem?

**Comment by lakinduakash** [comment]
Can you change the. `complain` to `aa-complain ` in https://github.com/lakinduakash/linux-wifi-hotspot/blob/8612a0fc00e0565787d1cc49129ba8ab722f031b/src/scripts/create_ap#L1855 and https://github.com/lakinduakash/linux-wifi-hotspot/blob/8612a0fc00e0565787d1cc49129ba8ab722f031b/src/scripts/create_ap#L1858. Change it and reinstall the program.

**Comment by stevenfang1997** [comment]
Sorry for the late reply. I think this might be a Manjaro problem. Once I switched to Fedora, the problem was gone.

**Comment by bananasmoothii** [comment]
Hi, I am also on manjaro (gnome) and I fixed it with this with `sudo ln -s /usr/bin/aa-complain /usr/bin/complain`. For me, I could not start the AP no matter what I've tried.

**Comment by bananasmoothii** [comment]
Ok I ended up reinstalling windows on my laptop because I just could not get it to work (the AP was activated but I couldn't see it)
