### ISSUE TITLE
Hidden checkbox does not seem to hide the network

### ISSUE THREAD

**Issue by NotSqrt** [lakinduakash/linux-wifi-hotspot#69]
**Describe the bug**
`create_ap` should be called with the `--hidden` flag when the `Hidden` checkbox of the GUI is checked.

**To Reproduce**
1. configure a network in the GUI
2. check the `Hidden` checkbox
3. Create the hotspot
4. check on other device if the network is visible or hidden : yes
5. check options used to launch `create_ap` : not `--hidden`

**Expected behavior**

`create_ap` should be called with the `--hidden` flag.

Manually calling `sudo create_ap --config /etc/wh.config --hidden` does the job.

**Desktop :**
 - OS: Ubuntu 18.04
 - Version: linux-wifi-hotspot 3.0.0

**Comment by lakinduakash** [comment]
When you click the start button if the hidden box is checked it writes the correct value to `/etc/wh.config`. And then start it using that written config file. Can you check the value of `HIDDEN=1` or `HIDDEN=0` in `/etc/wh.config` after you starting the AP with the hidden box checked?

**Comment by NotSqrt** [comment]
`HIDDEN=1` is in `/etc/wh.config`.

**Comment by NotSqrt** [comment]
It seems to be working correctly now, so maybe it was just a slow scan from my Android client, sorry to bother you.

**Comment by NotSqrt** [comment]
Maybe there's some troubles when applying parameters :
`FREQ_BAND=2.4` in the `/etc/wh.config` file + `--freq-band 2.4` argument : no problem.
`FREQ_BAND=2.4` in the `/etc/wh.config` file + no `--freq-band 2.4` argument : `create_ap` wants to use the 5GHz band.

**Comment by lakinduakash** [comment]
@NotSqrt If you are connected to 5Ghz network already it automatically selects 5Ghz band. Also, there are issues with making AP with 5Ghz  in some Linux drivers. To avoid that select 2.4Ghz manually.
