### ISSUE TITLE
add more wi-fi secerity options for older WIIFI cards

### ISSUE THREAD

**Issue by Littlemac123** [lakinduakash/linux-wifi-hotspot#72]
I been trying to play Nintendo DS online and the Nintendo DS can only connect to wep 40/128 WIFI... and open.
and yeah yeah blah blah i can get hacked blah blah but i only use it every now and then anyway and i live in a old people area 
so I dont care but it would be nice to have more options like that in this app.

all so I cant do it in windows 10 at all cuz they lock you down to only using WPA2, cant even just have it open like your app can
so thats why i been looking for alternatives like this and I dont wanna just open it witch the DS can connect to but still... i dont want open even tho wep basically is open just for hackers.

**Comment by lakinduakash** [comment]
Currently, I don't have time to implement such new features. You can configure `hostapd.conf` to implement that and use the command line if can put some onto it. Here is a sample configuration file of hostapd https://gist.github.com/renaudcerrato/db053d96991aba152cc17d71e7e0f63c
