### ISSUE TITLE
No rule to make target '../build/resources.o', needed by '../build/wihotspot-gui'

### ISSUE THREAD

**Issue by yochananmarqos** [lakinduakash/linux-wifi-hotspot#73]
**Describe the bug**
Same build failure as reported in Issue #68:

```
mkdir -p build
Run 'sudo make install' for installation.
Run 'sudo make uninstall' for uninstallation.
cd src && make
make[1]: Entering directory '/home/yochanan/Documents/AUR/linux-wifi-hotspot/src/linux-wifi-hotspot-3.1.0/src'
/usr/bin/glib-compile-resources ui/glade/wifih.gresource.xml --target=ui/resources.c --sourcedir=ui/glade --generate-source
gcc -c -o ../build/main.o ui/main.c `pkg-config --cflags gtk+-3.0`
gcc -c -o ../build/ui.o ui/ui.c `pkg-config --cflags gtk+-3.0`
gcc -c -o ../build/h_prop.o ui/h_prop.c `pkg-config --cflags gtk+-3.0`
gcc -c -o ../build/util.o ui/util.c `pkg-config --cflags gtk+-3.0`
g++ -c -o ../build/read_config.o ui/read_config.cpp
make[1]: *** No rule to make target '../build/resources.o', needed by '../build/wihotspot-gui'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/yochanan/Documents/AUR/linux-wifi-hotspot/src/linux-wifi-hotspot-3.1.0/src'
make: *** [Makefile:5: all] Error 2
```

**To Reproduce**
Build AUR package using `makepkg -si`

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: GNOME 3.38.1

**Additional context**
When I updated the AUR package to 3.0.0, it built fine. Now that I'm attempting to update to 3.1.0, I encountered this issue.

**Comment by lakinduakash** [comment]
It seems like generated resources.c file is not seen by the subsequent compilation command. So object file is not generated for resources.c.

I think it is completely okay if you build from git clone.

**Comment by yochananmarqos** [comment]
I switched the source from the tarball to using the git tag with the same result.

```
source=("git+https://github.com/lakinduakash/linux-wifi-hotspot#tag=v$pkgver")
```

**Comment by sigmadrelo** [comment]
Can you clone the git repository separately and try to build?

**Comment by lakinduakash** [comment]
Can you clone the git repository separately and try to build?

**Comment by yochananmarqos** [comment]
You seem to be missing the point here. It doesn't matter if it works building it on my system, this is an issue packaging it for the AUR. The source() array I posted above clones the repo at that tagged commit.

**Comment by lakinduakash** [comment]
Actually, I did not make any changes to `Makefile` from 3.0.0 to 3.1.0. I can not figure out why.

Can you explain little how AUR packaging work since I see this line

> `make[1]: Entering directory '/home/yochanan/Documents/AUR/linux-wifi-hotspot/src/linux-wifi-hotspot-3.1.0/src'`
It goes into `src` directory two times. 

Also there is a file called `resources.c` that is generated at build time. That file should be in `linux-wifi-hotspot/src/ui` after `/usr/bin/glib-compile-resources ui/glade/wifih.gresource.xml --target=ui/resources.c --sourcedir=ui/glade --generate-source`
command. It seems like it is not placing the correct directory. So when compiling the object files that `resources.c` file is not at the correct directory. I also need to investigate more because normally it builds without any issue. I will check using Manjaro VM

**Comment by yochananmarqos** [comment]
The `src` directory is the `SRCDEST`. See [Makepkg: Package output](https://wiki.archlinux.org/index.php/Makepkg#Package_output)

```
~/Documents/AUR/linux-wifi-hotspot
❯ tree
.
├── gitgo.sh
├── linux-wifi-hotspot
│   ├── branches
│   ├── config
│   ├── description
│   ├── FETCH_HEAD
│   ├── HEAD
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   └── update.sample
│   ├── info
│   │   └── exclude
│   ├── objects
│   │   ├── info
│   │   └── pack
│   │       ├── pack-9bee54175f589bbdcfda2cf2ae8dbf6c0f352f3a.idx
│   │       └── pack-9bee54175f589bbdcfda2cf2ae8dbf6c0f352f3a.pack
│   ├── packed-refs
│   └── refs
│       ├── heads
│       └── tags
├── linux-wifi-hotspot-3.1.0.tar.gz
├── linux-wifi-hotspot.install
├── pkg [error opening dir]
├── PKGBUILD
└── src
    ├── linux-wifi-hotspot
    │   ├── build
    │   │   ├── h_prop.o
    │   │   ├── main.o
    │   │   ├── read_config.o
    │   │   ├── ui.o
    │   │   └── util.o
    │   ├── CODE_OF_CONDUCT.md
    │   ├── CONTRIBUTING.md
    │   ├── docs
    │   │   ├── howto
    │   │   │   └── realtek.md
    │   │   ├── sc1.png
    │   │   └── sc2.png
    │   ├── LICENSE
    │   ├── Makefile
    │   ├── Makefile.cmake
    │   ├── README.md
    │   ├── snapcraft.yaml
    │   └── src
    │       ├── CMakeLists.txt
    │       ├── desktop
    │       │   ├── hotspot.png
    │       │   └── wifihotspot.desktop
    │       ├── Makefile
    │       ├── scripts
    │       │   ├── bash_completion
    │       │   ├── create_ap
    │       │   ├── create_ap.conf
    │       │   ├── create_ap.service
    │       │   ├── LICENSE
    │       │   ├── Makefile
    │       │   ├── README.md
    │       │   ├── sudors_edit.sh
    │       │   └── wihotspot
    │       └── ui
    │           ├── glade
    │           │   ├── style.css
    │           │   ├── wifih.gresource.xml
    │           │   └── wifih.ui
    │           ├── h_prop.c
    │           ├── h_prop.h
    │           ├── main.c
    │           ├── read_config.cpp
    │           ├── read_config.h
    │           ├── resources.c
    │           ├── ui.c
    │           ├── ui.h
    │           ├── util.c
    │           └── util.h
    └── linux-wifi-hotspot#tag=3.1.0 -> /home/yochanan/Documents/AUR/linux-wifi-hotspot/linux-wifi-hotspot#tag=3.1.0

21 directories, 66 files
```

**Comment by lakinduakash** [comment]
Can you put the `PKGBUILD` script for this?

**Comment by yochananmarqos** [comment]
It's in the AUR: [`linux-wifi-hotspot`](https://aur.archlinux.org/packages/linux-wifi-hotspot). See [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository).

**Comment by lakinduakash** [comment]
I made some fixes.
I tested myself with `makepkg -s`. Check it at [v3.1.1](https://github.com/lakinduakash/linux-wifi-hotspot/releases/tag/v3.1.1).

Give me feedback afterward. :)

**Comment by yochananmarqos** [comment]
3.1.1 builds fine, thanks.

You're right, `glade` isn't necessary. Not sure how it got there, probably @ragouel added it for some reason.
