### ISSUE TITLE
Hotspot cannot be discovered despite the application is running

### ISSUE THREAD

**Issue by stevenfang1997** [lakinduakash/linux-wifi-hotspot#75]
I'm on Fedora 32.

I could create a hotspot on 2.4 frequency brand and the application said the hotspot was running. However, I couldn't find my hotspot at all on the network setting. I tried both on WPA & WPA2 Enterprise and WPA & WPA2 Personal network and the results were the same. Here is the screenshot of my settings:
![image](https://user-images.githubusercontent.com/37974764/95648427-ae89eb80-0b22-11eb-8898-648592c88093.png)

Here is the command line output: 
`pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'whatisahotspot' '' --mkconfig /etc/wh.config --freq-band 2.4`
`Config options written to '/etc/wh.config`

Did I do anything wrong in the hotspot settings? Is there anyway to fix this? Thank you!

**Comment by lakinduakash** [comment]
Does it work with a password?

**Comment by stevenfang1997** [comment]
> Does it work with a password?

Nope.

**Comment by lakinduakash** [comment]
Sometimes it may be slow discovering of your device as in #69. Also, try with `create_ap` command line with multiple combinations such as enabling **ieee80211n** with `sudo create_ap --ieee80211n wlp0s20f3 wlp0s20f3 MyAccessPoint MyPassPhrase`

Refer here for more examples https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/src/scripts/README.md

**Comment by stevenfang1997** [comment]
Thank you for your help. Please reopen this issue as the issue is not solved yet.

I have tried various `create_ap` combinations. They created hotspot successfully and I could find the hotspot and input the password, but I couldn't make other devices connect to the hotspot. For example, I tried to use my Android phone to connect to the hotspot and it stuck with "obtaining IP address". Here is an example command line output:

`$ sudo create_ap --ieee80211n wlp0s20f3 wlp0s20f3 MyAccessPoint MyPassPhrase --freq-band 2.4`
`Config dir: /tmp/create_ap.wlp0s20f3.conf.baavG1Y9`
`PID: 16244`
`Network Manager found, set ap0 as unmanaged device... DONE`
`Custom frequency band set with 2.4Mhz with channel 1`
`Creating a virtual WiFi interface... ap0 created.`
`Sharing Internet using method: nat`
`hostapd command-line interface: hostapd_cli -p /tmp/create_ap.wlp0s20f3.conf.baavG1Y9/hostapd_ctrl`
`Configuration file: /tmp/create_ap.wlp0s20f3.conf.baavG1Y9/hostapd.conf`
`ap0: interface state UNINITIALIZED->HT_SCAN`
`20/40 MHz operation not permitted on channel pri=1 sec=5 based on overlapping BSSes`
`Using interface ap0 with hwaddr 64:5d:86:d7:52:18 and ssid "MyAccessPoint"`
`ap0: interface state HT_SCAN->ENABLED`
`ap0: AP-ENABLED` 
`ap0: STA 28:c6:71:00:83:2a IEEE 802.11: authenticated`
`ap0: STA 28:c6:71:00:83:2a IEEE 802.11: associated (aid 1)`
`ap0: AP-STA-CONNECTED 28:c6:71:00:83:2a`
`ap0: STA 28:c6:71:00:83:2a RADIUS: starting accounting session FBDCC20885EDDD28`
`ap0: STA 28:c6:71:00:83:2a WPA: pairwise key handshake completed (RSN)`
`ap0: AP-STA-DISCONNECTED 28:c6:71:00:83:2a`
`ap0: STA 28:c6:71:00:83:2a IEEE 802.11: authenticated`
`ap0: STA 28:c6:71:00:83:2a IEEE 802.11: associated (aid 1)`
`ap0: AP-STA-CONNECTED 28:c6:71:00:83:2a`
`ap0: STA 28:c6:71:00:83:2a RADIUS: starting accounting session DB73D072F7B3D654`
`ap0: STA 28:c6:71:00:83:2a WPA: pairwise key handshake completed (RSN)`
`^Cap0: interface state ENABLED->DISABLED`
`ap0: AP-STA-DISCONNECTED 28:c6:71:00:83:2a`

**Comment by lakinduakash** [comment]
That's strange. I need to investigate more about this issue. There might be an issue with DHCP. Can you try to put a static IP in the client?

**Comment by stevenfang1997** [comment]
Can you tell me how to put a static IP in the client? I can't any tutorial on that.

**Comment by lakinduakash** [comment]
That's depend on your device. If it is android go to wifi setting and then select the network. Then you can select between DHCP and Static. Add gateway as 192.168.12.1 and assign IP addresses of your choice (must match to prefix/subnet)  ex: 192.168.12.90

**Comment by felixmde** [comment]
> Sometimes it may be slow discovering of your device as in #69. Also, try with `create_ap` command line with multiple combinations such as enabling **ieee80211n** with `sudo create_ap --ieee80211n wlp0s20f3 wlp0s20f3 MyAccessPoint MyPassPhrase`
> 
> Refer here for more examples https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/src/scripts/README.md

I had the same problem on Arch Linux where the tool would start properly, but my devices could not find the AP. I was able to resolve the issue using the suggested **ieee80211n**.

For reference, I now use the following command on Arch to create a working AP:

`sudo create_ap --ieee80211n wlp4s0 enp0s25 apname secretpw`

Thanks @lakinduakash for this package. It's awesome.

**Comment by lakinduakash** [comment]
> > Sometimes it may be slow discovering of your device as in #69. Also, try with `create_ap` command line with multiple combinations such as enabling **ieee80211n** with `sudo create_ap --ieee80211n wlp0s20f3 wlp0s20f3 MyAccessPoint MyPassPhrase`
> > Refer here for more examples https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/src/scripts/README.md
> 
> I had the same problem on Arch Linux where the tool would start properly, but my devices could not find the AP. I was able to resolve the issue using the suggested **ieee80211n**.
> 
> For reference, I now use the following command on Arch to create a working AP:
> 
> `sudo create_ap --ieee80211n wlp4s0 enp0s25 apname secretpw`
> 
> Thanks @lakinduakash for this package. It's awesome.

Nice!
I will add GUI option to enable that too. 😊

**Comment by lakinduakash** [comment]
@felixmde 

I added GUI options to enable `ieee80211n` and `ieee80211ac`. you can check them. :)

**Comment by ShrirajHegde** [comment]
I am on Fedora 35 and have the same problem

command : ` sudo create_ap --ieee80211n wlo1 wlo1 MyAccessPoint 12345678`

Output:
```
Config dir: /tmp/create_ap.wlo1.conf.k3hyjSXj
PID: 117339
Network Manager found, set ap0 as unmanaged device... DONE
wlo1 is already associated with channel 11 (2462 MHz)
multiple channels supported
Creating a virtual WiFi interface... ap0 created.
Sharing Internet using method: nat
hostapd command-line interface: hostapd_cli -p /tmp/create_ap.wlo1.conf.k3hyjSXj/hostapd_ctrl
Configuration file: /tmp/create_ap.wlo1.conf.k3hyjSXj/hostapd.conf
ap0: interface state UNINITIALIZED->HT_SCAN
20/40 MHz operation not permitted on channel pri=1 sec=5 based on overlapping BSSes
Using interface ap0 with hwaddr 34:e1:2d:9b:c1:5d and ssid "MyAccessPoint"
ap0: interface state HT_SCAN->ENABLED
ap0: AP-ENABLED 
ap0: STA ee:99:6d:5c:7c:ac IEEE 802.11: authenticated
ap0: STA ee:99:6d:5c:7c:ac IEEE 802.11: associated (aid 1)
ap0: AP-STA-CONNECTED ee:99:6d:5c:7c:ac
ap0: STA ee:99:6d:5c:7c:ac RADIUS: starting accounting session 9A730BB6EBBE0A1B
ap0: STA ee:99:6d:5c:7c:ac WPA: pairwise key handshake completed (RSN)
```
After this, phone is stuck in "Obtaining IP Address".

Using static IP connects to AP, but doesn't provide internet.
Settings used:

<img src=https://user-images.githubusercontent.com/66936172/150676613-67f1e5ae-34a3-4c62-b50e-676af204c46a.png width="400"/>
