### ISSUE TITLE
Not running...

### ISSUE THREAD

**Issue by lukenavo** [lakinduakash/linux-wifi-hotspot#76]
**Describe the bug**
Hi, I am trying to use your program because I want to share school teacher's wifi with students in my classrooom (students doesn 't have wifi connection). 
I'm working with Pentium core 2 duo, network wifi interface wpl8s0, system bunsenlab linux (debian 9).
Every time I tried to start connection the gui show some fast messages (I can't read them...) but every time the final conclusion is 
"Not running".

Can I've made some errors? Could be my pc too old?

Thank for your efforts!

**Comment by lakinduakash** [comment]
can you try with this and  `sudo create_ap wpl8s0 wpl8s0 MyAccessPoint MyPassPhrase` put output?

**Comment by lukenavo** [comment]
Ok I get this:

Config dir: /tmp/create_ap.wlp8s0.conf.5mPH7oAQ
PID: 1928
Network Manager found, set ap0 as unmanaged device... DONE
wlp8s0 is already associated with channel 1 (2412 MHz)channel------------------ 1
Creating a virtual WiFi interface... ap0 created.
/usr/bin/create_ap: line 1724: dnsmasq: command not found

ERROR: Wrong version format!

Doing cleanup.. done

**Comment by lakinduakash** [comment]
I think you did not install all the dependencies. Please install `dnsmasq`. If there will be additional `command not found` errors appear install them too

**Comment by lukenavo** [comment]
Ok! Now it is working! Thank you very much!
