### ISSUE TITLE
Can't run 'sudo make install'

### ISSUE THREAD

**Issue by sibylledL** [lakinduakash/linux-wifi-hotspot#80]
Hi, I just git clone the repo and when I run "sudo make install" I got this error :

 __No rule to make target '../build/wihotspot-gui', needed by 'install'.  Stop__

And the build folder is indeed empty, can you help me with that ?
Thank you
S.

**Comment by lakinduakash** [comment]
Can you put the whole output of compiling?

**Comment by sibylledL** [comment]
yes, it is : 

Installing...
cd src && make install
make[1]: Entering directory '/home/sibylle/Documents/linux-wifi-hotspot/src'
make[1]: *** No rule to make target '../build/wihotspot-gui', needed by 'install'.  Stop.
make[1]: Leaving directory '/home/sibylle/Documents/linux-wifi-hotspot/src'
make: *** [Makefile:9: install] Error 2

Thanks

**Comment by lakinduakash** [comment]
Did you execute `make` first and ended up without error?

You have to execute `make` first. Then execute `sudo make install`.

**Comment by sibylledL** [comment]
yes, i had an error running make.
here is my output of the command make: 

mkdir -p build
Run 'sudo make install' for installation.
Run 'sudo make uninstall' for uninstallation.
cd src && make
make[1]: Entering directory '/Documents/linux-wifi-hotspot/src'
/bin/sh: 0: Illegal option --
ui/glade/wifih.gresource.xml --target=ui/resources.c --sourcedir=ui/glade --generate-source
make[1]: execvp: ui/glade/wifih.gresource.xml: Permission denied
make[1]: *** [Makefile:32: resources.c] Error 127
make[1]: Leaving directory '/Documents/linux-wifi-hotspot/src'
make: *** [Makefile:5: all] Error 2

**Comment by lakinduakash** [comment]
Did you install all the dev dependencies stated in READMe.md? Specially `libgtk-3-dev` and `pkg-config`?

Can you put the output of `pkg-config --variable=glib_compile_resources gio-2.0` aslo?

It seems like your system doesn't have `glib-compile-resources` binary. 
What is your OS and version?

**Comment by sibylledL** [comment]
Ok so sorry, I didn't run "sudo apt install -y libgtk-3-dev build-essential gcc g++ pkg-config make hostapd".
It works now
(I'm on Linux, Debian 4.19.98-1)
Thank you

**Comment by lakinduakash** [comment]
Did you install `libqrencode-dev` and  `libpng-dev` ? If not please check the dependencies and install them

**Comment by Shud06** [comment]
Yes i install it

**Comment by Shud06** [comment]
Thanks it worked

**Comment by KaidenSkywalker** [comment]
having same error :D installed all known dependencies on steamos and cant run it :(
