### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by chromer030** [lakinduakash/linux-wifi-hotspot#87]
This software is using create_ap as backend , so it should be easy to provide an Appimage.
Please release Appimage too.
Will be great.

**Comment by lakinduakash** [comment]
This uses slightly modified create_ap version rather than original one. Anyway an appimage need to be self contained. I need to think more about it. Thank you about the issue.

**Comment by mutageneral** [comment]
Can we get an AppImage or Flatpak now? @lakinduakash This would be needed to use this program on the [Steam Deck](https://www.steamdeck.com/) as the SteamOS Linux distro has an immutable file system, similar to [Fedora Silverblue](https://silverblue.fedoraproject.org/). You can only install Flatpak or AppImage. I want to be able to make a Wi-Fi hotspot on the Steam Deck, so other device can connect to it and be able to play local multiplayer anywhere.
