### ISSUE TITLE
Not working on newest arch linux.

### ISSUE THREAD

**Issue by zw963** [lakinduakash/linux-wifi-hotspot#88]
**Describe the bug**
All seem like working, but, can not find hot spots on my android cell phone.

![image](https://user-images.githubusercontent.com/549126/97545905-a24ccc00-1a06-11eb-9b99-867b0c5465c9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Arch]
 - Version [HEAD]

**Additional context**
It's is not working when i run it use desktop file from gnome app search.
so, i have to run it manually in terminal.

**Comment by lakinduakash** [comment]
Does it work without setting the mac address?

**Comment by zw963** [comment]
No.

```
sh -c 'env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/bin/wihotspot'
pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'adfsda23232' '' --mkconfig /etc/wh.config --freq-band 2.4 
Config options written to '/etc/wh.config'

```

![image](https://user-images.githubusercontent.com/549126/97669090-52c9d700-1abe-11eb-90bf-2e272171803f.png)

**Comment by lakinduakash** [comment]
It seems running. Some times it takes minutes to appear the wifi access point in android devices. #69 

But it needs to be checked why that setting mac address giving an error

**Comment by zw963** [comment]
> It seems running. Some times it takes minutes to appear the wifi access point in android devices. #69

I guess not this case? because i start it several hours, but still can't see SSID.

following is my config:

```
CHANNEL=default
GATEWAY=192.168.12.1
WPA_VERSION=1+2
ETC_HOSTS=0
DHCP_DNS=gateway
NO_DNS=0
NO_DNSMASQ=0
HIDDEN=0
MAC_FILTER=0
MAC_FILTER_ACCEPT=/etc/hostapd/hostapd.accept
ISOLATE_CLIENTS=0
SHARE_METHOD=nat
IEEE80211N=0
IEEE80211AC=0
HT_CAPAB=[HT40+]
VHT_CAPAB=
DRIVER=nl80211
NO_VIRT=0
COUNTRY=
FREQ_BAND=2.4
NEW_MACADDR=
DAEMONIZE=0
DAEMON_PIDFILE=
DAEMON_LOGFILE=/dev/null
NO_HAVEGED=0
WIFI_IFACE=wlp0s20f3
INTERNET_IFACE=wlp0s20f3
SSID=adfsda23232
PASSPHRASE=
USE_PSK=0
```

**Comment by bryce-lynch** [comment]
Same here. I'll keep using create_ap for now.

**Comment by lakinduakash** [comment]
@zw963 which command you manually run that works for you? Do you use create_ap comes with this repository or the original one?

**Comment by lakinduakash** [comment]
@bryce-lynch can you provide more information about the bug?

**Comment by zw963** [comment]
> @zw963 which command you manually run that works for you? Do you use create_ap comes with this repository or the original one? 

In fact, both package not works for me.

**Comment by lakinduakash** [comment]
Enabling ieee80211n might work

**Comment by zw963** [comment]
Not working use newest github released version.

```sh
 ╰─ $   ./wihotspot-gui 
pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'MyAccessPoint' '12345678' --mkconfig /etc/create_ap.conf --freq-band 2.4 --ieee80211n  
Config options written to '/etc/create_ap.conf'
iptables v1.8.7 (legacy): unknown option "--to-ports"
Try `iptables -h' or 'iptables --help' for more information.
Command not found or exited with error status
```

Following is the content of `/etc/create_ap.conf`

```
CHANNEL=default
GATEWAY=192.168.12.1
WPA_VERSION=2
ETC_HOSTS=0
DHCP_DNS=gateway
NO_DNS=0
NO_DNSMASQ=0
HIDDEN=0
MAC_FILTER=0
MAC_FILTER_ACCEPT=/etc/hostapd/hostapd.accept
ISOLATE_CLIENTS=0
SHARE_METHOD=nat
IEEE80211N=1
IEEE80211AC=0
HT_CAPAB=[HT40+]
VHT_CAPAB=
DRIVER=nl80211
NO_VIRT=0
COUNTRY=
FREQ_BAND=2.4
NEW_MACADDR=
DAEMONIZE=0
DAEMON_PIDFILE=
DAEMON_LOGFILE=/dev/null
NO_HAVEGED=0
WIFI_IFACE=wlp0s20f3
INTERNET_IFACE=wlp0s20f3
SSID=MyAccessPoint
PASSPHRASE=12345678
USE_PSK=0
```

**Comment by mingcenwei** [comment]
I use Arch Linux (5.11.11-arch1-1) with KDE. This app (installed from AUR) works fine on my laptop regardless of whether I start it from KRunner (GUI) or Konsole (terminal).

**Comment by lakinduakash** [comment]
@mingcenwei Thank you for the feedback.

**Comment by zw963** [comment]
linux-wifi-hotspot 4.0.3-1 works for me too on arch linux, thank you very much!
